export const lists = [
  {
    customer: {
      name: 'Approved Dev Test',
      uid: 'approveddev@diva-e.com',
      currency: { active: true, isocode: 'EUR', name: 'Euro', symbol: '€' },
      department: 'Abteilung approved dev',
      displayUid: 'approveddev@diva-e.com',
      fax: '03012312333',
      firstName: 'Approved Dev',
      language: {
        active: true,
        isocode: 'de',
        name: 'Deutsch',
        nativeName: 'Deutsch',
      },
      lastName: 'Test',
      ociBuyer: false,
      orgUnit: {
        name: 'Approved Dev',
        uid: 'DE-2601231516',
        active: true,
        addresses: [
          {
            billingAddress: true,
            companyName: 'Approved Dev',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            id: '8823585406999',
            line1: 'Markt ',
            line2: '1',
            postalCode: '07743',
            shippingAddress: false,
            town: 'Jena',
            visibleInAddressBook: true,
          },
          {
            billingAddress: false,
            companyName: 'Approved Dev',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            id: '8823585439767',
            line1: 'Markt ',
            line2: '1',
            postalCode: '07743',
            shippingAddress: true,
            town: 'Jena',
            visibleInAddressBook: true,
          },
          {
            billingAddress: false,
            companyName: 'asd',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            firstName: 'as',
            id: '8824797822999',
            lastName: 'asd',
            line1: 'asd',
            line2: '4',
            postalCode: '123455',
            shippingAddress: true,
            town: 'asdasd',
            visibleInAddressBook: true,
          },
          {
            billingAddress: false,
            companyName: 'qwe',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            firstName: 'qwe',
            id: '8824797855767',
            lastName: 'qwe',
            line1: 'ghj',
            postalCode: '1234',
            shippingAddress: true,
            town: 'fgh',
            visibleInAddressBook: true,
          },
        ],
        customerId: '2601231516',
        furtherDetails: 'weitere Angaben approved dev',
        vatID: '12345678',
      },
      phone: '030123123',
      registrationStatus: { code: 'APPROVED' },
    },
    description: '123',
    entries: [
      {
        amount: 528,
        price: {
          currencyIso: 'EUR',
          customerPrice: false,
          formattedValue: '74,89 €',
          priceType: 'BUY',
          value: 74.89,
        },
        product: {
          bullets: [
            'Kombinierter Pumpstand mit Turbopumpe und Vorpumpe für alle Anwendungen im Hochvakuum',
            'Luftgekühlt und betriebsfertig mit HiPace 300 und Drehschieberpumpe Pascal 2010',
            'Standardausführung mit 4 Rollen (ohne Kabelsatz für externen Betrieb)',
          ],
          categoryPath: [
            { id: 'PUMPING_STATIONS__SYSTEMS', name: 'Pumpstand Systeme' },
            { id: 'PUMPING_STATIONS', name: 'Pumpstände' },
            { id: 'HICUBE_PRO', name: 'HiCube Pro' },
          ],
          code: 'PM_S43_670_00_sample',
          configurable: false,
          images: [
            {
              altText: 'HiCube 300 Pro, DN 100 ISO-K, Pascal 2010',
              format: 'product',
              imageType: 'PRIMARY',
              url: '/medias/?context=bWFzdGVyfGltYWdlc3wzODU4NTN8aW1hZ2UvcG5nfGg2Ni9oZjgvODgyNDY4ODg2OTQwNnxmM2JjZGQ3M2Q0YWQ2YjdiYzY2MmE5YzY3NTdhNzU3OWM4YWFmODVhMThkMzY3NzQwNDcwMjM4OGUxYjUwOTNk',
            },
          ],
          master: '93bdf4d3-f195-428a-891d-b691b16ae9e1_sample',
          name: 'HiCube 300 Pro, DN 100 ISO-K, Pascal 2010',
          orderNumber: 'PM S43 670 00',
          productType: 'VARIANTPRODUCT',
          purchasable: true,
          url: '/Pumpstand-Systeme/Pumpst%C3%A4nde/HiCube-Pro/HiCube-300-Pro%2C-DN-100-ISO-K%2C-Pascal-2010/p/PM_S43_670_00_sample',
          variationMatrix: {
            allSelected: true,
            masterProductCode: '93bdf4d3-f195-428a-891d-b691b16ae9e1_sample',
            variantCodes: ['PM_S43_670_00_sample'],
            variationAttributes: [
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_2156.2156',
                name: 'Turbopumpe',
                variationValues: [
                  {
                    automaticallySelected: true,
                    displayValue: 'HiPace 300',
                    selectable: true,
                    selected: true,
                    value: 'HiPace 300',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_2029.2029',
                name: 'Vorpumpe',
                variationValues: [
                  {
                    automaticallySelected: false,
                    displayValue: 'ACP 15',
                    selectable: false,
                    selected: false,
                    value: 'ACP 15',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'ACP 28',
                    selectable: false,
                    selected: false,
                    value: 'ACP 28',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Duo 11 M',
                    selectable: false,
                    selected: false,
                    value: 'Duo 11 M',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Duo 20 M',
                    selectable: true,
                    selected: false,
                    value: 'Duo 20 M',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Pascal 2010',
                    selectable: true,
                    selected: true,
                    value: 'Pascal 2010',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Pascal 2021',
                    selectable: true,
                    selected: false,
                    value: 'Pascal 2021',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_2428.2428',
                name: 'Anschlussflansch (Eingang)',
                variationValues: [
                  {
                    automaticallySelected: true,
                    displayValue: 'DN 100 ISO-K',
                    selectable: true,
                    selected: true,
                    value: 'DN 100 ISO-K',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_3920.3920',
                name: 'Netzspannung',
                variationValues: [
                  {
                    automaticallySelected: false,
                    displayValue: '100 – 110 V AC, 50/60 Hz',
                    selectable: true,
                    selected: true,
                    value: '100 – 110 V AC, 50/60 Hz',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: '100 – 115 V AC, 50/60 Hz',
                    selectable: false,
                    selected: false,
                    value: '100 – 115 V AC, 50/60 Hz',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: '200 – 230 V AC, 50/60 Hz',
                    selectable: true,
                    selected: false,
                    value: '200 – 230 V AC, 50/60 Hz',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: '200 – 240 V AC, 50/60 Hz',
                    selectable: false,
                    selected: false,
                    value: '200 – 240 V AC, 50/60 Hz',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_3417.3417',
                name: 'Vorvakuum-Sicherheitsventil',
                variationValues: [
                  {
                    automaticallySelected: false,
                    displayValue: 'Ja',
                    selectable: true,
                    selected: false,
                    value: 'Ja',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Nein',
                    selectable: true,
                    selected: true,
                    value: 'Nein',
                  },
                ],
              },
            ],
          },
        },
      },
    ],
    id: '438011',
    lastModified: '2023-02-27T11:27:59+0000',
    name: 'PVWEB-1218-2',
  },
  {
    customer: {
      name: 'Approved Dev Test',
      uid: 'approveddev@diva-e.com',
      currency: { active: true, isocode: 'EUR', name: 'Euro', symbol: '€' },
      department: 'Abteilung approved dev',
      displayUid: 'approveddev@diva-e.com',
      fax: '03012312333',
      firstName: 'Approved Dev',
      language: {
        active: true,
        isocode: 'de',
        name: 'Deutsch',
        nativeName: 'Deutsch',
      },
      lastName: 'Test',
      ociBuyer: false,
      orgUnit: {
        name: 'Approved Dev',
        uid: 'DE-2601231516',
        active: true,
        addresses: [
          {
            billingAddress: true,
            companyName: 'Approved Dev',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            id: '8823585406999',
            line1: 'Markt ',
            line2: '1',
            postalCode: '07743',
            shippingAddress: false,
            town: 'Jena',
            visibleInAddressBook: true,
          },
          {
            billingAddress: false,
            companyName: 'Approved Dev',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            id: '8823585439767',
            line1: 'Markt ',
            line2: '1',
            postalCode: '07743',
            shippingAddress: true,
            town: 'Jena',
            visibleInAddressBook: true,
          },
          {
            billingAddress: false,
            companyName: 'asd',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            firstName: 'as',
            id: '8824797822999',
            lastName: 'asd',
            line1: 'asd',
            line2: '4',
            postalCode: '123455',
            shippingAddress: true,
            town: 'asdasd',
            visibleInAddressBook: true,
          },
          {
            billingAddress: false,
            companyName: 'qwe',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            firstName: 'qwe',
            id: '8824797855767',
            lastName: 'qwe',
            line1: 'ghj',
            postalCode: '1234',
            shippingAddress: true,
            town: 'fgh',
            visibleInAddressBook: true,
          },
        ],
        customerId: '2601231516',
        furtherDetails: 'weitere Angaben approved dev',
        vatID: '12345678',
      },
      phone: '030123123',
      registrationStatus: { code: 'APPROVED' },
    },
    description: '123',
    entries: [
      {
        amount: 528,
        price: {
          currencyIso: 'EUR',
          customerPrice: false,
          formattedValue: '74,89 €',
          priceType: 'BUY',
          value: 74.89,
        },
        product: {
          bullets: [
            'Kombinierter Pumpstand mit Turbopumpe und Vorpumpe für alle Anwendungen im Hochvakuum',
            'Luftgekühlt und betriebsfertig mit HiPace 300 und Drehschieberpumpe Pascal 2010',
            'Standardausführung mit 4 Rollen (ohne Kabelsatz für externen Betrieb)',
          ],
          categoryPath: [
            { id: 'PUMPING_STATIONS__SYSTEMS', name: 'Pumpstand Systeme' },
            { id: 'PUMPING_STATIONS', name: 'Pumpstände' },
            { id: 'HICUBE_PRO', name: 'HiCube Pro' },
          ],
          code: 'PM_S43_670_00_sample',
          configurable: false,
          images: [
            {
              altText: 'HiCube 300 Pro, DN 100 ISO-K, Pascal 2010',
              format: 'product',
              imageType: 'PRIMARY',
              url: '/medias/?context=bWFzdGVyfGltYWdlc3wzODU4NTN8aW1hZ2UvcG5nfGg2Ni9oZjgvODgyNDY4ODg2OTQwNnxmM2JjZGQ3M2Q0YWQ2YjdiYzY2MmE5YzY3NTdhNzU3OWM4YWFmODVhMThkMzY3NzQwNDcwMjM4OGUxYjUwOTNk',
            },
          ],
          master: '93bdf4d3-f195-428a-891d-b691b16ae9e1_sample',
          name: 'HiCube 300 Pro, DN 100 ISO-K, Pascal 2010',
          orderNumber: 'PM S43 670 00',
          productType: 'VARIANTPRODUCT',
          purchasable: true,
          url: '/Pumpstand-Systeme/Pumpst%C3%A4nde/HiCube-Pro/HiCube-300-Pro%2C-DN-100-ISO-K%2C-Pascal-2010/p/PM_S43_670_00_sample',
          variationMatrix: {
            allSelected: true,
            masterProductCode: '93bdf4d3-f195-428a-891d-b691b16ae9e1_sample',
            variantCodes: ['PM_S43_670_00_sample'],
            variationAttributes: [
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_2156.2156',
                name: 'Turbopumpe',
                variationValues: [
                  {
                    automaticallySelected: true,
                    displayValue: 'HiPace 300',
                    selectable: true,
                    selected: true,
                    value: 'HiPace 300',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_2029.2029',
                name: 'Vorpumpe',
                variationValues: [
                  {
                    automaticallySelected: false,
                    displayValue: 'ACP 15',
                    selectable: false,
                    selected: false,
                    value: 'ACP 15',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'ACP 28',
                    selectable: false,
                    selected: false,
                    value: 'ACP 28',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Duo 11 M',
                    selectable: false,
                    selected: false,
                    value: 'Duo 11 M',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Duo 20 M',
                    selectable: true,
                    selected: false,
                    value: 'Duo 20 M',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Pascal 2010',
                    selectable: true,
                    selected: true,
                    value: 'Pascal 2010',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Pascal 2021',
                    selectable: true,
                    selected: false,
                    value: 'Pascal 2021',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_2428.2428',
                name: 'Anschlussflansch (Eingang)',
                variationValues: [
                  {
                    automaticallySelected: true,
                    displayValue: 'DN 100 ISO-K',
                    selectable: true,
                    selected: true,
                    value: 'DN 100 ISO-K',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_3920.3920',
                name: 'Netzspannung',
                variationValues: [
                  {
                    automaticallySelected: false,
                    displayValue: '100 – 110 V AC, 50/60 Hz',
                    selectable: true,
                    selected: true,
                    value: '100 – 110 V AC, 50/60 Hz',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: '100 – 115 V AC, 50/60 Hz',
                    selectable: false,
                    selected: false,
                    value: '100 – 115 V AC, 50/60 Hz',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: '200 – 230 V AC, 50/60 Hz',
                    selectable: true,
                    selected: false,
                    value: '200 – 230 V AC, 50/60 Hz',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: '200 – 240 V AC, 50/60 Hz',
                    selectable: false,
                    selected: false,
                    value: '200 – 240 V AC, 50/60 Hz',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_3417.3417',
                name: 'Vorvakuum-Sicherheitsventil',
                variationValues: [
                  {
                    automaticallySelected: false,
                    displayValue: 'Ja',
                    selectable: true,
                    selected: false,
                    value: 'Ja',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Nein',
                    selectable: true,
                    selected: true,
                    value: 'Nein',
                  },
                ],
              },
            ],
          },
        },
      },
    ],
    id: '438012',
    lastModified: '2023-02-27T11:27:59+0000',
    name: 'PVWEB-1218-2',
  },
  {
    customer: {
      name: 'Approved Dev Test',
      uid: 'approveddev@diva-e.com',
      currency: { active: true, isocode: 'EUR', name: 'Euro', symbol: '€' },
      department: 'Abteilung approved dev',
      displayUid: 'approveddev@diva-e.com',
      fax: '03012312333',
      firstName: 'Approved Dev',
      language: {
        active: true,
        isocode: 'de',
        name: 'Deutsch',
        nativeName: 'Deutsch',
      },
      lastName: 'Test',
      ociBuyer: false,
      orgUnit: {
        name: 'Approved Dev',
        uid: 'DE-2601231516',
        active: true,
        addresses: [
          {
            billingAddress: true,
            companyName: 'Approved Dev',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            id: '8823585406999',
            line1: 'Markt ',
            line2: '1',
            postalCode: '07743',
            shippingAddress: false,
            town: 'Jena',
            visibleInAddressBook: true,
          },
          {
            billingAddress: false,
            companyName: 'Approved Dev',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            id: '8823585439767',
            line1: 'Markt ',
            line2: '1',
            postalCode: '07743',
            shippingAddress: true,
            town: 'Jena',
            visibleInAddressBook: true,
          },
          {
            billingAddress: false,
            companyName: 'asd',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            firstName: 'as',
            id: '8824797822999',
            lastName: 'asd',
            line1: 'asd',
            line2: '4',
            postalCode: '123455',
            shippingAddress: true,
            town: 'asdasd',
            visibleInAddressBook: true,
          },
          {
            billingAddress: false,
            companyName: 'qwe',
            country: { isocode: 'DE', name: 'Deutschland' },
            defaultAddress: false,
            firstName: 'qwe',
            id: '8824797855767',
            lastName: 'qwe',
            line1: 'ghj',
            postalCode: '1234',
            shippingAddress: true,
            town: 'fgh',
            visibleInAddressBook: true,
          },
        ],
        customerId: '2601231516',
        furtherDetails: 'weitere Angaben approved dev',
        vatID: '12345678',
      },
      phone: '030123123',
      registrationStatus: { code: 'APPROVED' },
    },
    description: '123',
    entries: [
      {
        amount: 528,
        price: {
          currencyIso: 'EUR',
          customerPrice: false,
          formattedValue: '74,89 €',
          priceType: 'BUY',
          value: 74.89,
        },
        product: {
          bullets: [
            'Kombinierter Pumpstand mit Turbopumpe und Vorpumpe für alle Anwendungen im Hochvakuum',
            'Luftgekühlt und betriebsfertig mit HiPace 300 und Drehschieberpumpe Pascal 2010',
            'Standardausführung mit 4 Rollen (ohne Kabelsatz für externen Betrieb)',
          ],
          categoryPath: [
            { id: 'PUMPING_STATIONS__SYSTEMS', name: 'Pumpstand Systeme' },
            { id: 'PUMPING_STATIONS', name: 'Pumpstände' },
            { id: 'HICUBE_PRO', name: 'HiCube Pro' },
          ],
          code: 'PM_S43_670_00_sample',
          configurable: false,
          images: [
            {
              altText: 'HiCube 300 Pro, DN 100 ISO-K, Pascal 2010',
              format: 'product',
              imageType: 'PRIMARY',
              url: '/medias/?context=bWFzdGVyfGltYWdlc3wzODU4NTN8aW1hZ2UvcG5nfGg2Ni9oZjgvODgyNDY4ODg2OTQwNnxmM2JjZGQ3M2Q0YWQ2YjdiYzY2MmE5YzY3NTdhNzU3OWM4YWFmODVhMThkMzY3NzQwNDcwMjM4OGUxYjUwOTNk',
            },
          ],
          master: '93bdf4d3-f195-428a-891d-b691b16ae9e1_sample',
          name: 'HiCube 300 Pro, DN 100 ISO-K, Pascal 2010',
          orderNumber: 'PM S43 670 00',
          productType: 'VARIANTPRODUCT',
          purchasable: true,
          url: '/Pumpstand-Systeme/Pumpst%C3%A4nde/HiCube-Pro/HiCube-300-Pro%2C-DN-100-ISO-K%2C-Pascal-2010/p/PM_S43_670_00_sample',
          variationMatrix: {
            allSelected: true,
            masterProductCode: '93bdf4d3-f195-428a-891d-b691b16ae9e1_sample',
            variantCodes: ['PM_S43_670_00_sample'],
            variationAttributes: [
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_2156.2156',
                name: 'Turbopumpe',
                variationValues: [
                  {
                    automaticallySelected: true,
                    displayValue: 'HiPace 300',
                    selectable: true,
                    selected: true,
                    value: 'HiPace 300',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_2029.2029',
                name: 'Vorpumpe',
                variationValues: [
                  {
                    automaticallySelected: false,
                    displayValue: 'ACP 15',
                    selectable: false,
                    selected: false,
                    value: 'ACP 15',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'ACP 28',
                    selectable: false,
                    selected: false,
                    value: 'ACP 28',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Duo 11 M',
                    selectable: false,
                    selected: false,
                    value: 'Duo 11 M',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Duo 20 M',
                    selectable: true,
                    selected: false,
                    value: 'Duo 20 M',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Pascal 2010',
                    selectable: true,
                    selected: true,
                    value: 'Pascal 2010',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Pascal 2021',
                    selectable: true,
                    selected: false,
                    value: 'Pascal 2021',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_2428.2428',
                name: 'Anschlussflansch (Eingang)',
                variationValues: [
                  {
                    automaticallySelected: true,
                    displayValue: 'DN 100 ISO-K',
                    selectable: true,
                    selected: true,
                    value: 'DN 100 ISO-K',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_3920.3920',
                name: 'Netzspannung',
                variationValues: [
                  {
                    automaticallySelected: false,
                    displayValue: '100 – 110 V AC, 50/60 Hz',
                    selectable: true,
                    selected: true,
                    value: '100 – 110 V AC, 50/60 Hz',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: '100 – 115 V AC, 50/60 Hz',
                    selectable: false,
                    selected: false,
                    value: '100 – 115 V AC, 50/60 Hz',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: '200 – 230 V AC, 50/60 Hz',
                    selectable: true,
                    selected: false,
                    value: '200 – 230 V AC, 50/60 Hz',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: '200 – 240 V AC, 50/60 Hz',
                    selectable: false,
                    selected: false,
                    value: '200 – 240 V AC, 50/60 Hz',
                  },
                ],
              },
              {
                code: 'pfeifferClassificationCatalog/1.0/cc_3417.3417',
                name: 'Vorvakuum-Sicherheitsventil',
                variationValues: [
                  {
                    automaticallySelected: false,
                    displayValue: 'Ja',
                    selectable: true,
                    selected: false,
                    value: 'Ja',
                  },
                  {
                    automaticallySelected: false,
                    displayValue: 'Nein',
                    selectable: true,
                    selected: true,
                    value: 'Nein',
                  },
                ],
              },
            ],
          },
        },
      },
    ],
    id: '438013',
    lastModified: '2023-02-27T11:27:59+0000',
    name: 'PVWEB-1218-2',
  },
]
export const selectMode = false
