variables:
  DOCKER_SERVICE_NAME: pvac-web-app-server
  DOCKER_IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}

stages:
  - build
  - test
  - analysis
  - build-docker-image
  - audit
  - deployment
  - cms-sync

include:
  - local: '/.gitlab-ci/container_structure_test.yml'
  - local: '/.gitlab-ci/build.yml'
  - local: '/.gitlab-ci/cms.yml'
  - local: '/.gitlab-ci/deploy.yml'
