variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_SERVICE_NAME: pvac-web-app-server

image: node:16-alpine

services:
  - docker:dind

stages:
  - build
  - test
  - analysis
  - build-docker-image
  - audit
  - cms
  - deployment
  - uat-deployment
  - uat-cms-migration
  - prd-deployment
  - prd-cms-migration

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .npm/
    - .nuxt/
    - node_modules/

include:
  - local: '/.gitlab-ci/container_structure_test.yml'
  - local: '/.gitlab-ci/build.yml'
  - local: '/.gitlab-ci/cms.yml'
  - local: '/.gitlab-ci/deploy.yml'
