.node-image:
  image: node:16-alpine
  tags:
    - docker_runner

variables:
  DOCKER_SERVICE_NAME: pvac-web-app-server
  DOCKER_IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}

stages:
  - build
  - test
  - analysis
  - package
  - audit
  - deployment
  - cms-sync

include:
  - local: '/.gitlab-ci/build.yml'
  - local: '/.gitlab-ci/test.yml'
  - local: '/.gitlab-ci/analysis.yml'
  - local: '/.gitlab-ci/package.yml'
  - local: '/.gitlab-ci/audit.yml'
  - local: '/.gitlab-ci/deploy.yml'
  - local: '/.gitlab-ci/cms.yml'
