.node-image:
  image: node:16-alpine
  tags:
    - docker_runner

build:
  extends: .node-image
  stage: build
  cache:
    - key: "${CI_PIPELINE_ID}-build-frontend"
      paths:
        - .npm/
        - .nuxt/
        - node_modules/
      policy: push
    - key: "${CI_PIPELINE_ID}-build-lsg"
      paths:
        - lsg-public/
      policy: push
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - npm run lsg:build
  artifacts:
    when: on_failure
    paths:
      - .npm/_logs
    expire_in: 3 week

lint:
  extends: .node-image
  stage: test
  needs: ["build"]
  cache:
    - key: "${CI_PIPELINE_ID}-build-frontend"
      paths:
        - .npm/
        - .nuxt/
        - node_modules/
      policy: pull
    - key: "${CI_PIPELINE_ID}-report"
      paths:
        - report/
      policy: push
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run lint:ci
  artifacts:
    when: always
    paths:
      - report/
    expire_in: 3 week

test:
  extends: .node-image
  stage: test
  needs: ["build"]
  cache:
    - key: "${CI_PIPELINE_ID}-build-frontend"
      paths:
        - .npm/
        - .nuxt/
        - node_modules/
      policy: pull
    - key: "${CI_PIPELINE_ID}-coverage"
      paths:
        - coverage/
      policy: push
  script:
    - npm ci --cache .npm --prefer-offline
    - NODE_ENV=test
    - npm test
  artifacts:
    when: always
    reports:
      junit: coverage/clover.xml
    paths:
      - coverage/
    expire_in: 3 week

sonar-qube:
  image: sonarsource/sonar-scanner-cli
  stage: analysis
  needs: ["test", "lint"]
  cache:
    - key: "${CI_PIPELINE_ID}-build-frontend"
      paths:
        - .npm/
        - .nuxt/
        - node_modules/
      policy: pull
    - key: "${CI_PIPELINE_ID}-report"
      paths:
        - report/
      policy: pull
    - key: "${CI_PIPELINE_ID}-coverage"
      paths:
        - coverage/
      policy: pull
  script:
    - sonar-scanner -Dsonar.login=${SONARQUBE_ACCESS_TOKEN}
  tags:
    - docker_runner
    - shared
  only:
    - develop

.build-docker-image:
  image: docker:git
  stage: build-docker-image
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
  services:
    - docker:dind
  cache: []
  before_script:
    - # disable gitlab warning for docker login
      echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  script:
    - docker build
      -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
      --build-arg PORT=${PORT}
      --build-arg NODE_ENV=${NODE_ENV}
      --build-arg BASE_URL="${CI_ENVIRONMENT_URL}"
      --build-arg CONSOLA_LEVEL=${CONSOLA_LEVEL}
      --build-arg STORYBLOK_SPACE_ID=${STORYBLOK_SPACE_ID}
      --build-arg STORYBLOK_OAUTH_TOKEN="${STORYBLOK_OAUTH_TOKEN}"
      --build-arg STORYBLOK_ACCESS_TOKEN="${STORYBLOK_ACCESS_TOKEN}"
      --build-arg STORYBLOK_VERSION="${STORYBLOK_VERSION}"
      --build-arg STORYBLOK_RESOLVE_RELATIONS="${STORYBLOK_RESOLVE_RELATIONS}"
      --build-arg STORYBLOK_RESOLVE_LINKS="${STORYBLOK_RESOLVE_LINKS}"
      --build-arg STORYBLOK_RESOLVE_ASSETS="${STORYBLOK_RESOLVE_ASSETS}"
      --build-arg STORYBLOK_CONTENT_TYPES="${STORYBLOK_CONTENT_TYPES}"
      --build-arg STORYBLOK_EXCLUDE_ROUTES="${STORYBLOK_EXCLUDE_ROUTES}"
      --build-arg DEFAULT_LANGUAGE_CODE="${DEFAULT_LANGUAGE_CODE}"
      --build-arg LANGUAGE_CODES="${LANGUAGE_CODES}"
      --build-arg CI_COMMIT_SHORT_SHA="${CI_COMMIT_SHORT_SHA}"
      --build-arg CI_COMMIT_REF_NAME="${CI_COMMIT_REF_NAME}"
      --build-arg CI_PROJECT_URL="${CI_PROJECT_URL}"
      --build-arg REGION_CODES="${REGION_CODES}"
      --build-arg DEFAULT_REGION_CODE="${DEFAULT_REGION_CODE}"
      --build-arg SHOP_BASE_URL="${SHOP_BASE_URL}"
      --build-arg SHOP_IMAGE_URL="${SHOP_IMAGE_URL}"
      --build-arg CONSOLA_LEVEL="${CONSOLA_LEVEL}"
      --build-arg CURRENT_REGION_CODE="${CURRENT_REGION_CODE}"
      --build-arg USERCENTRICS_PRIVACY_PATH="${USERCENTRICS_PRIVACY_PATH}"
      --build-arg USERCENTRICS_ID="${USERCENTRICS_ID}"
      --build-arg KEYCLOAK_BASE_URL="${KEYCLOAK_BASE_URL}"
      --build-arg KEYCLOAK_REALM_NAME="${KEYCLOAK_REALM_NAME}"
      --build-arg KEYCLOAK_CLIENT_ID="${KEYCLOAK_CLIENT_ID}"
      -f docker/Dockerfile .
  after_script:
    - # here we will push ALL created tags of an image
      docker push --all-tags ${DOCKER_IMAGE_NAME}
  tags:
    - dind_runner

build-frontend-docker-image-for-branch:
  extends: .build-docker-image
  needs: ["test", "lint"]
  environment:
    name: dev2
  except:
    - develop
    - main
    - tags

.build-docker-image-lsg:
  extends: .build-docker-image
  image: docker:git
  cache:
    - key: "${CI_PIPELINE_ID}-build-lsg"
      paths:
        - lsg-public/
      policy: pull
  script:
    - docker build -t ${DOCKER_IMAGE_NAME}:lsg-${CI_COMMIT_REF_SLUG} -f docker/DockerfileLSG .

build-lsg-docker-image-for-branch:
  extends: .build-docker-image-lsg
  needs: ["test", "lint"]
  except:
    - develop
    - main
    - tags

build-frontend-docker-image-for-develop:
  extends: .build-docker-image
  needs: ["sonar-qube"]
  environment:
    name: dev2
  only:
    - develop

build-lsg-docker-image-for-develop:
  extends: .build-docker-image-lsg
  needs: ["sonar-qube"]
  only:
    - develop

build-frontend-uat-docker-image-for-main-and-tags:
  extends: .build-docker-image
  needs: ["test", "lint"]
  variables:
    DOCKER_IMAGE_TAG: uat-${CI_COMMIT_REF_SLUG}
  environment:
    name: uat2
  only:
    - main
    - tags

tag-docker-image-latest-main:
  extends: .build-docker-image
  needs: ["build-frontend-uat-docker-image-for-main-and-tags"]
  script:
    - docker pull ${DOCKER_IMAGE_NAME}:uat-${CI_COMMIT_REF_SLUG}
    - docker tag ${DOCKER_IMAGE_NAME}:uat-${CI_COMMIT_REF_SLUG} ${DOCKER_IMAGE_NAME}:latest
  only:
    - main

build-frontend-prd-docker-image-for-tags:
  extends: .build-docker-image
  needs: ["test", "lint"]
  variables:
    DOCKER_IMAGE_TAG: prd-${CI_COMMIT_REF_SLUG}
  environment:
    name: prd
  only:
    - tags

tag-gitlab-nightly:
  needs: ["build-frontend-docker-image-for-develop"]
  image: docker:git
  stage: build-docker-image
  before_script:
    - git remote remove origin
    - git remote add origin https://"${CI_GITLAB_TAG_WRITE_TOKEN_USERNAME}:${CI_GITLAB_TAG_WRITE_TOKEN_PASSWORD}"@gitlab.diva-e.com/pvac/pvweb.git
  script:
    - git tag  "$(date +'%Y%m%d.%H%M')"
    - git push origin "$(date +'%Y%m%d.%H%M')"
  only:
    - schedules
  tags:
    - docker_runner
