build:
  extends: .node-image
  stage: build
  cache:
    - key: "${CI_PIPELINE_ID}-build-frontend"
      paths:
        - .npm/
        - .nuxt/
        - node_modules/
      policy: push
    - key: "${CI_PIPELINE_ID}-build-lsg"
      paths:
        - lsg-public/
      policy: push
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - npm run lsg:build
  artifacts:
    when: on_failure
    paths:
      - .npm/_logs
    expire_in: 3 week
