.node-image:
  image: node:16-alpine
  tags:
    - docker_runner

build:
  extends: .node-image
  stage: build
  script:
    - npm i
    # - npm run build
    # - npm run lsg:build
  artifacts:
    when: on_failure
    paths:
      - .npm/_logs
    expire_in: 3 week

# lint:
#   extends: .node-image
#   stage: test
#   needs: ['build']
#   script:
#     # - npm run lint:ci
#   artifacts:
#     when: always
#     paths:
#       - report/
#     expire_in: 3 week

test:
  extends: .node-image
  stage: test
  needs: ['build']
  script:
    - npm run test
  artifacts:
    when: always
    reports:
      junit: coverage/clover.xml
    paths:
      - coverage/
    expire_in: 3 week

sonar-qube:
  image: sonarsource/sonar-scanner-cli
  stage: analysis
  needs: ['test']
  script:
    - sonar-scanner -Dsonar.login=${SONARQUBE_ACCESS_TOKEN}
  tags:
    - docker_runner
  only:
    - develop

.build-docker-image:
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    DOCKER_IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
  image: docker:git
  stage: build-docker-image
  services:
    - docker:dind
  before_script:
    - # disable gitlab warning for docker login
      echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  script:
    - docker build
      -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
      --build-arg NODE_ENV=${NODE_ENV}
      --build-arg BASE_URL="${CI_ENVIRONMENT_URL}"
      --build-arg DOMAIN="${CI_ENVIRONMENT_URL}"
      --build-arg DEFAULT_LANGUAGE_CODE="${DEFAULT_LANGUAGE_CODE}"
      --build-arg STORYBLOK_OAUTH_TOKEN="${STORYBLOK_OAUTH_TOKEN}"
      --build-arg STORYBLOK_ACCESS_TOKEN="${STORYBLOK_ACCESS_TOKEN}"
      --build-arg STORYBLOK_SPACE_ID=${STORYBLOK_SPACE_ID}
      --build-arg STORYBLOK_VERSION="${STORYBLOK_VERSION}"
      --build-arg STORYBLOK_RESOLVE_RELATIONS="${STORYBLOK_RESOLVE_RELATIONS}"
      --build-arg STORYBLOK_RESOLVE_LINKS="${STORYBLOK_RESOLVE_LINKS}"
      --build-arg STORYBLOK_RESOLVE_ASSETS="${STORYBLOK_RESOLVE_ASSETS}"
      --build-arg STORYBLOK_CONTENT_TYPES="${STORYBLOK_CONTENT_TYPES}"
      --build-arg STORYBLOK_EXCLUDE_ROUTES="${STORYBLOK_EXCLUDE_ROUTES}"
      -f docker/Dockerfile .
  after_script:
    - # here we will push ALL created tags of an image
      docker push --all-tags ${DOCKER_IMAGE_NAME}
  tags:
    - dind_runner

build-docker-image-frontend:
  extends: .build-docker-image
  needs: ['test']
  environment:
    name: dev2
  except:
    - develop

build-docker-image-lsg:
  extends: .build-docker-image
  needs: ['test']
  script:
    - docker build -t ${DOCKER_IMAGE_NAME}:lsg-${CI_COMMIT_REF_SLUG} -f docker/DockerfileLSG .
  except:
    - develop

build-docker-image-frontend-develop:
  extends: .build-docker-image
  needs: ['sonar-qube']
  environment:
    name: dev2
  only:
    - develop

build-docker-image-lsg-develop:
  extends: .build-docker-image
  needs: ['sonar-qube']
  script:
    - docker build -t ${DOCKER_IMAGE_NAME}:lsg-${CI_COMMIT_REF_SLUG} -f docker/DockerfileLSG .
  only:
    - develop

tag-docker-image-latest-main:
  extends: .build-docker-image
  needs: ['build-docker-image-frontend']
  script:
    - docker pull ${DOCKER_IMAGE_NAME}:main
    - docker tag ${DOCKER_IMAGE_NAME}:main ${DOCKER_IMAGE_NAME}:latest
  only:
    - main

build-docker-image-frontend-uat-tags:
  extends: .build-docker-image
  needs: ['test']
  variables:
    DOCKER_IMAGE_TAG: uat-${CI_COMMIT_REF_SLUG}
  environment:
    name: uat
  only:
    - tags

build-docker-image-frontend-prd-tags:
  extends: .build-docker-image
  needs: ['test']
  variables:
    DOCKER_IMAGE_TAG: prd-${CI_COMMIT_REF_SLUG}
  environment:
    name: prd
  only:
    - tags
