build:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    when: always
    paths:
      - .npm/_logs
    expire_in: 3 week
  tags:
    - docker_runner


lint:
  stage: test
  script:
    - npm run lint
  tags:
    - docker_runner

test:
  stage: test
  script:
    - npm test
  tags:
    - docker_runner
  artifacts:
    when: always
    reports:
      junit: coverage/clover.xml
    paths:
      - coverage/
    expire_in: 3 week

sonar-qube:
  stage: analysis
  script:
    - npm test
  tags:
    - docker_runner

.docker-image:
  image: docker:git
  stage: build-docker-image
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
  after_script:
    - # here we will push ALL created tags of an image
      docker push --all-tags ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}
  tags:
    - dind_runner

build-docker-image-branch:
  extends: .docker-image
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_BRANCH} .
  except:
    - tags

build-docker-image-tag:
  extends: .docker-image
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_TAG} .
  only:
    - tags

tag-latest-docker-image:
  extends: .docker-image
  script:
    - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_BRANCH}
    - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_BRANCH} ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:latest
  only:
    - main
