build:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    when: always
    paths:
      - .npm/_logs
    expire_in: 3 week
  tags:
    - docker_runner

lint:
  stage: test
  script:
    - npm run lint
  tags:
    - docker_runner

test:
  stage: test
  script:
    - npm test
  tags:
    - docker_runner

sonar-qube:
  stage: analysis
  script:
    - npm test
  tags:
    - docker_runner

build-docker-image:
  image: docker:git
  stage: build-docker-image
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker login ${CI_REGISTRY}
    - docker build --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHA} --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} -t ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_BRANCH} .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_BRANCH}
  tags:
    - docker_runner
  except:
    - tags

tag-docker-image:
  image: docker:git
  stage: build-docker-image
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker login ${CI_REGISTRY}
    - docker build --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHA} --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} -t  ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_TAG} .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_TAG}
  only:
    - tags
  tags:
    - docker_runner
  except:
    - schedules
