build:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    when: on_failure
    paths:
      - .npm/_logs
    expire_in: 3 week
  tags:
    - docker_runner


lint:
  stage: test
  script:
    - npm run lint
  tags:
    - docker_runner

test:
  stage: test
  script:
    - npm test
  tags:
    - docker_runner
  artifacts:
    when: always
    reports:
      junit: coverage/clover.xml
    paths:
      - coverage/
    expire_in: 3 week

sonar-qube:
  stage: analysis
  script:
    - npm test
  tags:
    - docker_runner

.docker-image:
  image: docker:git
  stage: build-docker-image
  before_script:
    - # disable gitlab warning for docker login
      echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  after_script:
    - # here we will push ALL created tags of an image
      docker push --all-tags ${IMAGE_NAME}
  tags:
    - dind_runner

build-docker-image-branch:
  extends: .docker-image
  script:
    - docker build -t ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} .
  except:
    - tags

build-docker-image-tag:
  extends: .docker-image
  script:
    - docker build -t ${IMAGE_NAME}:${CI_COMMIT_TAG} .
  only:
    - tags

tag-latest-docker-image:
  extends: .docker-image
  script:
    - docker pull ${IMAGE_NAME}:main
    - docker tag ${IMAGE_NAME}:main ${IMAGE_NAME}:latest
  only:
    - main
