.cms-migrate:
  stage: cms
  before_script:
    - cp ./cms/storyblok.${CI_ENVIRONMENT_NAME}.env ./cms/storyblok.env
  script:
    - npm run cms:migrate-components
    - npm run cms:migrate-content
  tags:
    - docker_runner
  environment:
    name: dev
    url: https://${CI_ENVIRONMENT_NAME}-vacuum.westeurope.cloudapp.azure.com
  except:
    - schedules
    - tags

cms-migrate-develop:
  extends: .cms-migrate
  environment:
    name: dev2
  only:
    refs:
      - develop

cms-migrate-develop-manuel:
  extends: .cms-migrate
  environment:
    name: dev2
  when: manual
  only:
    - tags

cms-migrate-uat:
  extends: .cms-migrate
  stage: uat-cms-migration
  environment:
    name: uat
  only:
    - tags
  allow_failure: true
  except: []

cms-migrate-production:
  extends: .cms-migrate
  stage: prd-cms-migration
  environment:
    name: prd
  only:
    - tags
  except: []
