.cms-migrate:
  extends: .node-image
  stage: cms-migration
  before_script:
    - # cp ./cms/storyblok.${CI_ENVIRONMENT_NAME}.env ./cms/storyblok.env
      echo "Laeuft davor..."
  script:
    - # npm run cms:migrate-components
      echo "Laeuft 1"
    - # npm run cms:migrate-content
      echo "Laeuft 2"
  environment:
    name: dev
    url: https://${CI_ENVIRONMENT_NAME}-vacuum.westeurope.cloudapp.azure.com

cms-migrate-dev-automatically-develop:
  extends: .cms-migrate
  needs: [ "deploy-dev-automatically" ]
  environment:
    name: dev2
  only:
    - develop

cms-migrate-dev-develop:
  extends: cms-migrate-dev-automatically-develop
  needs: [ "deploy-dev-manually-develop" ]

cms-migrate-dev:
  extends: .cms-migrate
  needs: [ "deploy-dev-manually" ]
  environment:
    name: dev2
  except:
    - develop

cms-migrate-uat-automatically:
  extends: .cms-migrate
  needs: [ "deploy-uat-automatically" ]
  environment:
    name: uat
  only:
    - main

cms-migrate-uat:
  extends: .cms-migrate
  needs: [ "deploy-uat-manually" ]
  environment:
    name: uat
  only:
    - tags
    - main

cms-migrate-production:
  extends: .cms-migrate
  needs: [ "deploy-prd-manually" ]
  environment:
    name: prd
  only:
    - tags
