.cms-sync:
  extends: .node-image
  stage: cms-sync
  cache:
    - key: "${CI_PIPELINE_ID}-build-frontend"
      paths:
        - .npm/
        - .nuxt/
        - node_modules/
      policy: pull
  script:
    - npm run cms:sync:ci --space "${STORYBLOK_SPACE_ID}" --token "${STORYBLOK_OAUTH_TOKEN}"

cms-sync-dev-automatically-develop:
  extends: .cms-sync
  needs: [ "deploy-dev-automatically" ]
  environment:
    name: dev2
  only:
    - develop

cms-sync-dev-develop:
  extends: cms-sync-dev-automatically-develop
  needs: [ "deploy-dev-manually-develop" ]

cms-sync-dev:
  extends: .cms-sync
  needs: [ "deploy-dev-manually" ]
  environment:
    name: dev2
  except:
    - develop

cms-sync-uat-automatically:
  extends: .cms-sync
  needs: [ "deploy-uat-automatically" ]
  environment:
    name: uat2
  only:
    - main

cms-sync-uat:
  extends: .cms-sync
  needs: [ "deploy-uat-manually" ]
  environment:
    name: uat2
  only:
    - tags
    - main

cms-sync-production:
  extends: .cms-sync
  needs: [ "deploy-prd-manually" ]
  environment:
    name: prd
  only:
    - tags
