schemaVersion: '2.0.0'

commandTests:
  - name: 'node'
    command: 'node'
    args: ['--version']
    expectedOutput: [ "v16\\.[0-9]+\\.[0-9]+" ]
    exitCode: 0
  - name: 'npm'
    command: 'npm'
    args: ['-v']
    expectedOutput: ["8\\.[0-9]+\\.[0-9]+"]
    exitCode: 0

metadataTest:
  env:
    - key: NODE_PROFILE
      value: "ci"
    - key: PORT
      value: "3000"
  exposedPorts: ["3000"]
  cmd: ["npm","start"]
  workdir: "/opt/pvac-frontend"
