include:
  - local: '/.gitlab-ci/container_structure_test.template.yml'

.audit_frontend:
  stage: audit
  extends: .container-structure-test
  variables:
    # Basic for git ci runner setup (docker in docker)
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
  cache: {}
  tags:
    - docker
  script:
    - echo "Run container structure test for image ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker pull ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    - container-structure-test test --image ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} --config .gitlab-ci/container_structure_test.config.yml

audit-frontend:
  extends: .audit_frontend
  needs: [ "build-docker-image-frontend" ]
  except:
    - develop

audit-frontend-develop:
  extends: .audit_frontend
  needs: [ "build-docker-image-frontend-develop" ]
  only:
    - develop

audit-frontend-uat:
  extends: .audit_frontend
  needs: [ "build-docker-image-frontend-uat-tags" ]
  variables:
    DOCKER_IMAGE_TAG: uat-${CI_COMMIT_REF_SLUG}
  only:
    - tags

audit-frontend-prd:
  extends: .audit_frontend
  needs: [ "build-docker-image-frontend-prd-tags" ]
  variables:
    DOCKER_IMAGE_TAG: prd-${CI_COMMIT_REF_SLUG}
  only:
    - tags

