schemaVersion: "2.0.0"

commandTests:
  - name: "node"
    command: "node"
    args: ["--version"]
    expectedOutput: ["v16\\.[0-9]+\\.[0-9]+"]
    exitCode: 0
  - name: "npm"
    command: "npm"
    args: ["-v"]
    expectedOutput: ["8\\.[0-9]+\\.[0-9]+"]
    exitCode: 0

metadataTest:
  envVars:
    - key: PORT
      value: ${PORT}
    - key: HOST
      value: ${HOST}
    - key: BASE_URL
      value: "${BASE_URL}"
    - key: NODE_ENV
      value: ${NODE_ENV}
    - key: DEFAULT_LANGUAGE_CODE
      value: "${DEFAULT_LANGUAGE_CODE}"
    - key: LANGUAGE_CODES
      value: "${LANGUAGE_CODES}"
    - key: REGION_CODES
      value: "${REGION_CODES}"
    - key: DEFAULT_REGION_CODE
      value: "${DEFAULT_REGION_CODE}"
    - key: CURRENT_REGION_CODE
      value: "${CURRENT_REGION_CODE}"
    - key: STORYBLOK_OAUTH_TOKEN
      value: ${STORYBLOK_OAUTH_TOKEN}
    - key: STORYBLOK_ACCESS_TOKEN
      value: ${STORYBLOK_ACCESS_TOKEN}
    - key: STORYBLOK_SPACE_ID
      value: ${STORYBLOK_SPACE_ID}
    - key: STORYBLOK_VERSION
      value: ${STORYBLOK_VERSION}
    - key: STORYBLOK_RESOLVE_RELATIONS
      value: "${STORYBLOK_RESOLVE_RELATIONS}"
    - key: STORYBLOK_RESOLVE_LINKS
      value: "${STORYBLOK_RESOLVE_LINKS}"
    - key: STORYBLOK_RESOLVE_ASSETS
      value: "${STORYBLOK_RESOLVE_ASSETS}"
    - key: STORYBLOK_CONTENT_TYPES
      value: "${STORYBLOK_CONTENT_TYPES}"
    - key: CI_COMMIT_SHORT_SHA
      value: "${CI_COMMIT_SHORT_SHA}"
    - key: CI_COMMIT_REF_NAME
      value: "${CI_COMMIT_REF_NAME}"
    - key: CI_PROJECT_URL
      value: "${CI_PROJECT_URL}"
    - key: SHOP_BASE_URL
      value: "${SHOP_BASE_URL}"
    - key: SHOP_IMAGE_URL
      value: "${SHOP_IMAGE_URL}"
    - key: CONSOLA_LEVEL
      value: "${CONSOLA_LEVEL}"
    - key: USERCENTRICS_PRIVACY_PATH
      value: "${USERCENTRICS_PRIVACY_PATH}"
    - key: USERCENTRICS_ID
      value: "${USERCENTRICS_ID}"
    - key: KEYCLOAK_BASE_URL
      value: "${KEYCLOAK_BASE_URL}"
    - key: KEYCLOAK_REALM_NAME
      value: "${KEYCLOAK_REALM_NAME}"
    - key: KEYCLOAK_CLIENT_ID
      value: "${KEYCLOAK_CLIENT_ID}"
    - key: EMPOLIS_TIMEOUT
      value: "${EMPOLIS_TIMEOUT}"
    - key: EMPOLIS_STAGE
      value: "${EMPOLIS_STAGE}"
    - key: EMPOLIS_PATH
      value: "${EMPOLIS_PATH}"
    - key: EMPOLIS_GUEST_TOKEN_URL
      value: "${EMPOLIS_GUEST_TOKEN_URL}"
    - key: EMPOLIS_SSO_PATH
      value: "${EMPOLIS_SSO_PATH}"
    - key: EMPOLIS_AUTH_URL
      value: "${EMPOLIS_AUTH_URL}"
    - key: EMPOLIS_USERNAME_CUSTOMER
      value: "${EMPOLIS_USERNAME_CUSTOMER}"
    - key: EMPOLIS_PASSWORD_CUSTOMER
      value: "${EMPOLIS_PASSWORD_CUSTOMER}"
    - key: EMPOLIS_USERNAME_INTERNAL_LEVEL_0
      value: "${EMPOLIS_USERNAME_INTERNAL_LEVEL_0}"
    - key: EMPOLIS_PASSWORD_INTERNAL_LEVEL_0
      value: "${EMPOLIS_PASSWORD_INTERNAL_LEVEL_0}"
    - key: EMPOLIS_USERNAME_INTERNAL_LEVEL_1
      value: "${EMPOLIS_USERNAME_INTERNAL_LEVEL_1}"
    - key: EMPOLIS_PASSWORD_INTERNAL_LEVEL_1
      value: "${EMPOLIS_PASSWORD_INTERNAL_LEVEL_1}"
    - key: EMPOLIS_USERNAME_INTERNAL_LEVEL_2
      value: "${EMPOLIS_USERNAME_INTERNAL_LEVEL_2}"
    - key: EMPOLIS_PASSWORD_INTERNAL_LEVEL_2
      value: "${EMPOLIS_PASSWORD_INTERNAL_LEVEL_2}"
    - key: EMPOLIS_CLIENT_ID
      value: "${EMPOLIS_CLIENT_ID}"
    - key: EMPOLIS_CLIENT_SECRET
      value: "${EMPOLIS_CLIENT_SECRET}"
    - key: GOOGLE_TAG_MANAGER_ID
      value: "${GOOGLE_TAG_MANAGER_ID}"
    - key: VACUUM_CALCULATOR_BASE_URL
      value: "${VACUUM_CALCULATOR_BASE_URL}"

  cmd: ["npm", "start"]
  workdir: "/opt/pvac-frontend"
