include:
  - local: '/.gitlab-ci/container_structure_test.template.yml'

.audit_frontend:
  stage: audit
  extends: .container-structure-test
  variables:
    # Basic for git ci runner setup (docker in docker)
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
  cache: {}
  tags:
    - dind_runner
  script:
    - echo "Prepare container for structure test for image ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    - apk add gettext
    - echo "Run container structure test for image ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    - cat .gitlab-ci/container_structure_test.config.yml | envsubst >> container_structure_test.config.${CI_COMMIT_SHORT_SHA}.yml
    - # disable gitlab warning for docker login
    echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
    - docker pull ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    - container-structure-test test --image ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} --config container_structure_test.config.${CI_COMMIT_SHORT_SHA}.yml

audit-frontend-branch:
  extends: .audit_frontend
  needs: [ "build-frontend-docker-image-for-branch" ]
  environment:
    name: dev2
  except:
    - develop
    - tags
    - main

audit-frontend-develop:
  extends: .audit_frontend
  needs: [ "build-frontend-docker-image-for-develop" ]
  environment:
    name: dev2
  only:
    - develop

audit-frontend-uat:
  extends: .audit_frontend
  needs: [ "build-frontend-uat-docker-image-for-main-and-tags" ]
  environment:
    name: uat2
  variables:
    DOCKER_IMAGE_TAG: uat-${CI_COMMIT_REF_SLUG}
  only:
    - tags
    - main

audit-frontend-prd:
  extends: .audit_frontend
  needs: [ "build-frontend-prd-docker-image-for-tags" ]
  environment:
    name: prd
  variables:
    DOCKER_IMAGE_TAG: prd-${CI_COMMIT_REF_SLUG}
  only:
    - tags

