schemaVersion: '2.0.0'

commandTests:
  - name: 'node'
    command: 'node'
    args: ['--version']
    expectedOutput: ["v16.*.*"]
    exitCode: 0
  - name: 'npm'
    command: 'npm'
    args: ['-v']
    expectedOutput: ["6.14"]
    exitCode: 0

metadataTest:
  env:
    - key: NUXT_HOST
      value: "0.0.0.0"
    - key: NUXT_PORT
      value: "3000"
  exposedPorts: ["3000"]
  cmd: ["npm","start"]
  workdir: "/opt/pvac-frontend"
