# general deployment configuration
# environment.name has to be set in extending configurations
.deployment:
  stage: deployment
  variables:
    DOCKER_HOST: ""
    IMAGE_NAME: ${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_BRANCH}
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
  script:
    - docker pull ${CI_REGISTRY}/${IMAGE_NAME}
    - docker-compose down
    - docker-compose up -d --no-deps --build
  environment:
    url: https://${CI_ENVIRONMENT_NAME}-vacuum.westeurope.cloudapp.azure.com
  tags:
    - pvacviewer-${CI_ENVIRONMENT_NAME}-deployment

# scheduled deployment for nightly dev2
deploy-dev:
  extends: .deployment
  environment:
    name: dev2
  only:
    - schedules

# manual deployment for dev2
deploy-dev-manually:
  extends: .deployment
  variables:
    IMAGE_NAME: ${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_TAG}
  environment:
    name: dev2
  when: manual
  only:
    - tags

deploy-uat:
  extends: .deployment
  stage: uat-deployment
  script:
    - docker service update --with-registry-auth --image ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_BRANCH} ${DOCKER_SERVICE_NAME}
  environment:
    name: uat
  when: manual
  allow_failure: false
  only:
    refs:
      - main

deploy-uat-manually:
  extends: .deployment
  stage: uat-deployment
  script:
    - docker service update --with-registry-auth --image ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_TAG} ${DOCKER_SERVICE_NAME}
  environment:
    name: uat
  when: manual
  allow_failure: false
  only:
    - tags

deploy-prd-manually:
  extends: .deployment
  stage: prd-deployment
  script:
    - docker service update --with-registry-auth --image ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_TAG} ${DOCKER_SERVICE_NAME}
  environment:
    name: prd
  when: manual
  allow_failure: false
  only:
    - tags
