# general deployment configuration
# environment.name has to be set in extending configurations
.deployment:
  stage: deployment
  before_script:
    - # disable gitlab warning for docker login
      echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  environment:
    url: https://${CI_ENVIRONMENT_NAME}-vacuum.westeurope.cloudapp.azure.com
  tags:
    - pvacviewer-${CI_ENVIRONMENT_NAME}-deployment

# scheduled deployment for nightly dev2
deploy-dev:
  extends: .deployment
  script:
    - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${$CI_COMMIT_REF_SLUG}
    - docker-compose down
    - docker-compose up -d --no-deps --build
  environment:
    name: dev2
  only:
    refs:
      - develop

# manual deployment for dev2
deploy-dev-manually:
  extends: .deployment
  script:
    - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_TAG}
    - docker-compose down
    - docker-compose up -d --no-deps --build
  environment:
    name: dev2
  when: manual
  only:
    - tags

deploy-uat:
  extends: .deployment
  stage: uat-deployment
  script:
    - docker service update --with-registry-auth --image ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:main ${DOCKER_SERVICE_NAME}
  environment:
    name: uat
  when: manual
  allow_failure: false
  only:
    refs:
      - main

deploy-uat-manually:
  extends: .deployment
  stage: uat-deployment
  script:
    - docker service update --with-registry-auth --image ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_TAG} ${DOCKER_SERVICE_NAME}
  environment:
    name: uat
  when: manual
  allow_failure: false
  only:
    - tags

deploy-prd-manually:
  extends: .deployment
  stage: prd-deployment
  script:
    - docker service update --with-registry-auth --image ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}:${CI_COMMIT_TAG} ${DOCKER_SERVICE_NAME}
  environment:
    name: prd
  when: manual
  allow_failure: false
  only:
    - tags
