# general deployment configuration
# environment.name has to be set in extending configurations
.deployment:
  stage: deployment
  cache: {}
  variables:
    DOCKER_IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}
    DOCKER_IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
  before_script:
    - # disable gitlab warning for docker login
      echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}

.deploy-on-dev-machine:
  extends: .deployment
  needs: [ "audit-frontend" ]
  variables:
    DOCKER_COMPOSE_FILENAME: ""
    DOCKER_SERVICE_NAME: ""
  script:
    - docker build
      --build-arg NODE_ENV=${NODE_ENV}
      --build-arg DEFAULT_LANGUAGE_CODE='${DEFAULT_LANGUAGE_CODE}'
      --build-arg STORYBLOK_OAUTH_TOKEN='${STORYBLOK_OAUTH_TOKEN}'
      --build-arg STORYBLOK_ACCESS_TOKEN
      --build-arg STORYBLOK_SPACE_ID='${STORYBLOK_SPACE_ID}'
      --build-arg STORYBLOK_VERSION='${STORYBLOK_VERSION}'
      --build-arg STORYBLOK_RESOLVE_RELATIONS='${STORYBLOK_RESOLVE_RELATIONS}'
      --build-arg STORYBLOK_RESOLVE_LINKS='${STORYBLOK_RESOLVE_LINKS}'
      --build-arg STORYBLOK_RESOLVE_ASSETS='${STORYBLOK_RESOLVE_ASSETS}'
      --build-arg STORYBLOK_CONTENT_TYPES='${STORYBLOK_CONTENT_TYPES}'
      --build-arg STORYBLOK_EXCLUDE_ROUTES='${STORYBLOK_EXCLUDE_ROUTES}'
      -f docker/Dockerfile .
    - export container_running=`docker container list | grep ${DOCKER_SERVICE_NAME}`
    - # check if container is running. stop and remove if so.
      if [ -n container_running ]; then
        docker-compose -f ${DOCKER_COMPOSE_FILENAME} stop ${DOCKER_SERVICE_NAME};
        docker-compose -f ${DOCKER_COMPOSE_FILENAME} rm --force ${DOCKER_SERVICE_NAME};
      fi;
    - docker-compose -f ${DOCKER_COMPOSE_FILENAME} up --detach --no-deps --build ${DOCKER_SERVICE_NAME}
  environment:
    name: ${DOCKER_SERVICE_NAME}
    url: https://dev-vacuum.westeurope.cloudapp.azure.com/${DOCKER_SERVICE_NAME}
  tags:
    - pvac-frontend-dev2-deployment

# scheduled deployment for nightly dev2
deploy-dev-automatically:
  extends: .deploy-on-dev-machine
  needs: [ "audit-frontend-develop" ]
  variables:
    DOCKER_COMPOSE_FILENAME: "docker/docker-compose-frontend.yml"
    DOCKER_SERVICE_NAME: "dev2"
  only:
    - develop

# manual deployment for dev2
deploy-dev-manually-develop:
  extends: deploy-dev-automatically
  when: manual

# scheduled deployment for nightly lsg
deploy-lsg-automatically:
  extends: .deploy-on-dev-machine
  needs: [ "build-docker-image-lsg-develop" ]
  variables:
    DOCKER_COMPOSE_FILENAME: "docker/docker-compose-lsg.yml"
    DOCKER_IMAGE_TAG: "lsg-${CI_COMMIT_REF_SLUG}"
    DOCKER_SERVICE_NAME: "lsg"
  only:
    - develop

deploy-lsg-manually-develop:
  extends: deploy-lsg-automatically
  when: manual

# manual deployment for dev2
deploy-dev-manually:
  extends: .deploy-on-dev-machine
  variables:
    DOCKER_COMPOSE_FILENAME: "docker/docker-compose-frontend.yml"
    DOCKER_SERVICE_NAME: "dev2"
  when: manual
  except:
    - develop

# manual deployment for lsg
deploy-lsg-manually:
  extends: .deploy-on-dev-machine
  needs: [ "build-docker-image-lsg" ]
  variables:
    DOCKER_COMPOSE_FILENAME: "docker/docker-compose-lsg.yml"
    DOCKER_IMAGE_TAG: "lsg-${CI_COMMIT_REF_SLUG}"
    DOCKER_SERVICE_NAME: "lsg"
  when: manual
  except:
    - develop

deploy-uat-automatically:
  extends: .deployment
  script:
    - docker service update --with-registry-auth --image ${DOCKER_IMAGE_NAME}:main ${DOCKER_SERVICE_NAME}
  environment:
    name: uat
  when: manual
  allow_failure: false
  only:
    - main
  tags:
    - pvac-frontend-uat-deployment

deploy-uat-manually:
  extends: .deployment
  script:
    - docker service update --with-registry-auth --image ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG} ${DOCKER_SERVICE_NAME}
  environment:
    name: uat
  when: manual
  allow_failure: false
  only:
    - tags
  tags:
    - pvac-frontend-uat-deployment

deploy-prd-manually:
  extends: .deployment
  script:
    - docker service update --with-registry-auth --image ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG} ${DOCKER_SERVICE_NAME}
  environment:
    name: prd
  when: manual
  allow_failure: false
  only:
    - tags
  tags:
    - pvac-frontend-prd-deployment
