export const products = [
  {
    categories: [{ id: 'HIPACE__800', name: 'HiPace® 800' }],
    categoryPath: [
      { id: 'PUMPS', name: 'Pumps' },
      { id: 'TURBOPUMPS', name: 'Turbopumps' },
      { id: 'HIPACE__800', name: 'HiPace® 800' },
    ],
    code: 'f35d5da3-6db5-4175-aa5b-0ba195e3789a_sample',
    configurable: false,
    description: '',
    images: [
      {
        altText: 'HiPace® 800 M with TM 700, DN 200 CF-F',
        format: 'product',
        imageType: 'PRIMARY',
        url: '/medias/?context=bWFzdGVyfGltYWdlc3wzNzg3OTR8aW1hZ2UvcG5nfGg3YS9oZmYvODgyNDY4ODY0MDAzMHxhYzQ4NTRkMzMwOTM2YmNkNjcwMWE4YTk2NTRkZmViZTc4OTRhZjQ4ODU3YzlkZTZiZjk4YmIyMWE5MGM1ZGY5',
      },
    ],
    name: 'HiPace® 800',
    numberOfVariants: 18,
    priceRange: {},
    productType: 'MASTERPRODUCT',
    purchasable: false,
    stock: { stockLevel: 0, stockLevelStatus: 'outOfStock' },
    summary: '',
    url: '/Pumps/Turbopumps/HiPace%C2%AE-800/HiPace%C2%AE-800/p/f35d5da3-6db5-4175-aa5b-0ba195e3789a_sample',
  },
  {
    bullets: [
      '5-axis magnetically levitated turbopump with a pumping speed of 790 l/s for N<sub>2</sub>',
      'Integrated digital magnetic bearing controller TM 700',
      'Installation in any orientation, flexible through connectivity of up to 4 accessory parts',
      'With integrated water cooling for maximum gas throughput',
      'Interfaces, RS-485, Remote (Profibus/DeviceNet on request)',
      'The turbopump features extremely low vibration and is oil-free',
      'With In-field sensor calibration',
      'Including venting valve for pulsed venting',
      'Protection Class, IP 54',
      'Extensive accessories expand the range of applications',
    ],
    categories: [{ id: 'HIPACE__800', name: 'HiPace® 800' }],
    categoryPath: [
      { id: 'PUMPS', name: 'Pumps' },
      { id: 'TURBOPUMPS', name: 'Turbopumps' },
      { id: 'HIPACE__800', name: 'HiPace® 800' },
    ],
    code: 'PM_P04_464_sample',
    configurable: false,
    description: '',
    images: [
      {
        altText: 'HiPace® 800 M with TM 700, Profibus, DN 200 ISO-F',
        format: 'product',
        imageType: 'PRIMARY',
        url: '/medias/?context=bWFzdGVyfGltYWdlc3wzNjc4OTd8aW1hZ2UvcG5nfGgyNS9oZmMvODgyNDY4ODczODMzNHw0NTNmZDEyZjJkZmYyNmY2NGFjYzg2NWI3MGM0MzBkY2YwNGFlZTdjZDVlMTBmYjExZmM4NDYyNjllM2ViN2I5',
      },
      {
        altText: 'HiPace® 800 M with TM 700, Profibus, DN 200 ISO-F',
        format: 'product',
        galleryIndex: 0,
        imageType: 'GALLERY',
        url: '/medias/?context=bWFzdGVyfGltYWdlc3wzMDc4MHxpbWFnZS9wbmd8aGU1L2g4NS84ODI0Njg3MTY1NDcwfDQ3YjI5YzM1YzM3M2ExNzFlZmNlNTAxMTc2NGViNGM3MTBlMzhhYTMzMDVmNWRiZWE3YmVhZjk3NTk1NGNlNDg',
      },
      {
        altText: 'HiPace® 800 M with TM 700, Profibus, DN 200 ISO-F',
        format: 'product',
        galleryIndex: 1,
        imageType: 'GALLERY',
        url: '/medias/?context=bWFzdGVyfGltYWdlc3w2MTA3OXxpbWFnZS9wbmd8aDRiL2g4Yy84ODI0Njg3MzI5MzEwfGRmODY1ZWJjYTI5NThkYzU0NWVjYjAxNTYwODU0YzhhYTZmNzhjYmRiMWQ1MWUyZjVlYTM0OGJmOWEwMWIwMGY',
      },
    ],
    master: 'f35d5da3-6db5-4175-aa5b-0ba195e3789a_sample',
    name: 'HiPace® 800 M with TM 700, Profibus, DN 200 ISO-F',
    orderNumber: 'PM P04 464',
    priceRange: {},
    productReferences: [
      {
        referenceType: 'ACCESSORIES',
        target: {
          code: 'PM_Z01_205_B_sample',
          name: 'TVV 001, fore-vacuum safety valve, 230 V AC',
          url: '/c/TVV-001%2C-fore-vacuum-safety-valve%2C-230-V-AC/p/PM_Z01_205_B_sample',
        },
        preselected: false,
      },
      {
        referenceType: 'ACCESSORIES',
        target: {
          code: 'PM_Z01_206_B_sample',
          name: 'TVV 001, fore-vacuum safety valve, 115 V AC',
          url: '/c/TVV-001%2C-fore-vacuum-safety-valve%2C-115-V-AC/p/PM_Z01_206_B_sample',
        },
        preselected: false,
      },
      {
        referenceType: 'ACCESSORIES',
        target: {
          code: 'PT_R70_000_sample',
          name: 'TIC 010, adapter for two sensors',
          url: '/c/TIC-010%2C-adapter-for-two-sensors/p/PT_R70_000_sample',
        },
        preselected: false,
      },
    ],
    productType: 'VARIANTPRODUCT',
    purchasable: true,
    stock: { stockLevelStatus: 'inStock' },
    summary: '',
    typedFeatureList: [
      {
        code: 'TechnicalData',
        features: [
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2023.2023',
            comparable: true,
            featureValues: [{ value: 'TM 700' }],
            name: 'Electronic drive unit',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2025.2025',
            comparable: true,
            featureValues: [{ value: 'YES' }],
            name: 'Low oscillation',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2055.2055',
            comparable: true,
            featureUnit: { name: 'W', symbol: 'W', unitType: 'power' },
            featureValues: [{ value: '300' }],
            name: 'Power consumption max.',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2090.2090',
            comparable: true,
            featureUnit: {
              name: 'mT',
              symbol: 'mT',
              unitType: 'magneticfluxdensity',
            },
            featureValues: [{ value: '5' }],
            name: 'Permissible radial magnetic field max.',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2096.2096',
            comparable: true,
            featureUnit: { name: 'min', symbol: 'min', unitType: 'time' },
            featureValues: [{ value: '4' }],
            name: 'Run-up time',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2127.2127',
            comparable: true,
            featureValues: [{ value: '80 l/h' }],
            name: 'Cooling water flow',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2150.2150',
            comparable: true,
            featureValues: [{ value: 'IP54' }],
            name: 'Protection degree',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2157.2157',
            comparable: true,
            featureValues: [{ value: 'Arbitrary' }],
            name: 'Mounting orientation',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2180.2180',
            comparable: true,
            featureValues: [{ value: 'Magnet' }],
            name: 'Bearing',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2366.2366',
            comparable: true,
            featureValues: [{ value: 'RS-485, Remote, Profibus' }],
            name: 'I/O interfaces',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2368.2368',
            comparable: true,
            featureValues: [{ value: 'Profibus' }],
            name: 'Interfaces, extended',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2424.2424',
            comparable: true,
            featureValues: [{ value: 'DN 25 ISO-KF' }],
            name: 'Connection flange (out)',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2428.2428',
            comparable: true,
            featureValues: [{ value: 'DN 200 ISO-F' }],
            name: 'Connection flange (in)',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2673.2673',
            comparable: true,
            featureUnit: { name: 'kg', symbol: 'kg', unitType: 'weight' },
            featureValues: [{ value: '18' }],
            name: 'Weight',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2707.2707',
            comparable: true,
            featureValues: [{ value: '48 (± 5 %) V DC' }],
            name: 'Operating voltage: V DC',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2730.2730',
            comparable: true,
            featureUnit: {
              name: 'rpm',
              symbol: 'rpm',
              unitType: 'revolutionperminute',
            },
            featureValues: [{ value: '49200' }],
            name: 'Rotation speed ± 2 %',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2750.2750',
            comparable: true,
            featureValues: [{ value: '7,5 A' }],
            name: 'Current, max.',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2772.2772',
            comparable: true,
            featureValues: [{ value: '15 – 35 °C' }],
            name: 'Cooling water temperature',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2962.2962',
            comparable: true,
            featureValues: [{ value: "G 1/8''" }],
            name: 'Venting connection',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2977.2977',
            comparable: true,
            featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
            featureValues: [{ value: '< 1 · 10<sup>-7</sup>' }],
            name: 'Final pressure according to PNEUROP',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3137.3137',
            comparable: true,
            featureUnit: {
              name: 'm³/h',
              symbol: 'm³/h',
              unitType: 'volumeflow',
            },
            featureValues: [{ value: '80' }],
            name: 'Cooling water flow, max.',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3139.3139',
            comparable: true,
            featureUnit: {
              name: 'm³/h',
              symbol: 'm³/h',
              unitType: 'volumeflow',
            },
            featureValues: [{ value: '80' }],
            name: 'Cooling water flow, min.',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3167.3167',
            comparable: true,
            featureUnit: {
              name: 'm³/s',
              symbol: 'm³/s',
              unitType: 'volumeflow',
            },
            featureValues: [{ value: '625' }],
            name: 'Pumping speed for He',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3183.3183',
            comparable: true,
            featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
            featureValues: [{ value: '8' }],
            name: 'Fore-vacuum max. for N<sub>2</sub>',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3252.3252',
            comparable: true,
            featureValues: [{ value: 'Air/convection' }],
            name: 'Cooling method, optional',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3313.3313',
            comparable: true,
            featureValues: [{ value: '≤45 dB(A)' }],
            name: 'Sound pressure level',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3335.3335',
            comparable: true,
            featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
            featureValues: [{ value: '1 · 10<sup>-7</sup>' }],
            name: 'Final pressure without gas ballast',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3375.3375',
            comparable: true,
            featureUnit: {
              name: 'm³/s',
              symbol: 'm³/s',
              unitType: 'volumeflow',
            },
            featureValues: [{ value: '790' }],
            name: 'Pumping speed for N<sub>2</sub>',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3412.3412',
            comparable: true,
            featureValues: [{ value: '> 1 · 10<sup>11</sup>' }],
            name: 'Compression ratio for Ar',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3414.3414',
            comparable: true,
            featureValues: [{ value: '2 · 10<sup>5</sup>' }],
            name: 'Compression ratio for H<sub>2</sub>',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3415.3415',
            comparable: true,
            featureValues: [{ value: '> 1 · 10<sup>7</sup>' }],
            name: 'Compression ratio for He',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3416.3416',
            comparable: true,
            featureValues: [{ value: '> 1 · 10<sup>11</sup>' }],
            name: 'Compression ratio for N<sub>2</sub>',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3425.3425',
            comparable: true,
            featureUnit: {
              name: 'hPa·l/s',
              symbol: 'hPa·l/s',
              unitType: 'throughput',
            },
            featureValues: [{ value: '16' }],
            name: 'Gas throughput at 0.1 hPa HV pressure for Ar',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3427.3427',
            comparable: true,
            featureUnit: {
              name: 'hPa·l/s',
              symbol: 'hPa·l/s',
              unitType: 'throughput',
            },
            featureValues: [{ value: '9' }],
            name: 'Gas throughput at 0.1 hPa HV pressure for H<sub>2</sub>',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3428.3428',
            comparable: true,
            featureUnit: {
              name: 'hPa·l/s',
              symbol: 'hPa·l/s',
              unitType: 'throughput',
            },
            featureValues: [{ value: '16' }],
            name: 'Gas throughput at 0.1 hPa HV pressure for He',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3429.3429',
            comparable: true,
            featureUnit: {
              name: 'hPa·l/s',
              symbol: 'hPa·l/s',
              unitType: 'throughput',
            },
            featureValues: [{ value: '16' }],
            name: 'Gas throughput at 0.1 hPa HV pressure for N<sub>2</sub>',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3430.3430',
            comparable: true,
            featureUnit: {
              name: 'hPa·l/s',
              symbol: 'hPa·l/s',
              unitType: 'throughput',
            },
            featureValues: [{ value: '8' }],
            name: 'Gas throughput at final rotation speed for Ar',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3434.3434',
            comparable: true,
            featureUnit: {
              name: 'hPa·l/s',
              symbol: 'hPa·l/s',
              unitType: 'throughput',
            },
            featureValues: [{ value: '13' }],
            name: 'Gas throughput at final rotation speed for N<sub>2</sub>',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3436.3436',
            comparable: true,
            featureUnit: {
              name: 'm³/s',
              symbol: 'm³/s',
              unitType: 'volumeflow',
            },
            featureValues: [{ value: '775' }],
            name: 'Pumping speed for Ar',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3438.3438',
            comparable: true,
            featureUnit: {
              name: 'm³/s',
              symbol: 'm³/s',
              unitType: 'volumeflow',
            },
            featureValues: [{ value: '500' }],
            name: 'Pumping speed for H<sub>2</sub>',
            range: false,
            type: 'TechnicalData',
          },
        ],
      },
      {
        code: 'DownloadData',
        features: [
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_1108.1108',
            comparable: true,
            featureValues: [{ value: 'Installationshinweis_LabView.pdf' }],
            name: 'Software',
            range: false,
            type: 'DownloadData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3161.3161',
            comparable: true,
            featureValues: [{ value: 'PT0357' }],
            name: 'Operating instructions',
            range: false,
            type: 'DownloadData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3333.3333',
            comparable: true,
            featureValues: [{ value: 'PT0354' }],
            name: 'Operating instructions',
            range: false,
            type: 'DownloadData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3782.3782',
            comparable: true,
            featureValues: [{ value: 'Pfeiffer_Vacuum.zip' }],
            name: 'Software',
            range: false,
            type: 'DownloadData',
          },
        ],
      },
      {
        code: 'ClassifyData',
        features: [
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3389.3389',
            comparable: true,
            featureValues: [{ value: '1E-7 hPa' }],
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3390.3390',
            comparable: true,
            featureValues: [{ value: '1E-7 hPa' }],
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3795.3795',
            comparable: true,
            featureValues: [{ value: 'ISO-F' }],
            name: 'Main flange type',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3796.3796',
            comparable: true,
            featureValues: [{ value: 'DN 200' }],
            name: 'Main flange size',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3806.3806',
            comparable: true,
            featureValues: [{ value: 'Turbopumps' }],
            name: 'Product type',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3807.3807',
            comparable: true,
            featureValues: [{ value: 'HiPace® 800' }],
            name: 'Product',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3809.3809',
            comparable: true,
            featureValues: [{ value: 'Pumps' }],
            name: 'Product category',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3912.3912',
            comparable: true,
            featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
            featureValues: [{ value: '1.0E-7' }],
            name: 'Vacuum range min',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3913.3913',
            comparable: true,
            featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
            featureValues: [{ value: '8' }],
            name: 'Vacuum range max',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3914.3914',
            comparable: true,
            featureValues: [{ value: 'Integrated electronic drive unit' }],
            name: 'Electronic drive unit location',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3917.3917',
            comparable: true,
            featureUnit: {
              name: 'm³/h',
              symbol: 'm³/h',
              unitType: 'volumeflow',
            },
            featureValues: [{ value: '2880' }],
            name: 'Pumping Speed Class',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3918.3918',
            comparable: true,
            featureValues: [{ value: 'HiPace® 800' }],
            name: 'Master-Product',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3925.3925',
            comparable: true,
            featureValues: [{ value: '32038' }],
            name: 'Product-Master-ShortID',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3929.3929',
            comparable: true,
            featureValues: [{ value: 'External power supply pack' }],
            name: 'Power supply location',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3930.3930',
            comparable: true,
            featureValues: [{ value: 'RS-485, Remote, Profibus' }],
            name: 'I/O Interfaces',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3931.3931',
            comparable: true,
            featureValues: [{ value: '48 V DC' }],
            name: 'Operating voltage',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3942.3942',
            comparable: true,
            featureValues: [
              { value: 'M - For vibration-sensitive and oil-free processes' },
            ],
            name: 'Special Product Version',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3945.3945',
            comparable: true,
            featureValues: [{ value: 'with TM 700' }],
            name: 'Electronic drive unit',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3950.3950',
            comparable: true,
            featureValues: [{ value: 'DN 200 ISO-F' }],
            name: 'Connection flange',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3952.3952',
            comparable: true,
            featureValues: [{ value: '36432490' }],
            name: 'eclass code',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3953.3953',
            comparable: true,
            featureValues: [{ value: '3643' }],
            name: 'eclass group',
            range: false,
            type: 'ClassifyData',
          },
        ],
      },
    ],
    url: '/Pumps/Turbopumps/HiPace%C2%AE-800/HiPace%C2%AE-800-M-with-TM-700%2C-Profibus%2C-DN-200-ISO-F/p/PM_P04_464_sample',
  },
  {
    bullets: [
      'Particularly well suited for glass flanges',
      'Not to be used for the installation of turbo pumps! Use the fastening elements given in the corresponding operating instructions.',
      'Suitable for use with elastomer seals',
    ],
    categories: [
      { id: 'CLAMPS_FOR_ELASTOMER_SEALS', name: 'Clamps for elastomer seals' },
    ],
    categoryPath: [
      { id: 'COMPONENTS__VALVES', name: 'Components & Valves' },
      { id: 'COMPONENTS', name: 'Components' },
      { id: 'FASTENING_ELEMENTS', name: 'Fastening elements' },
      { id: 'CLAMPS_FOR_ELASTOMER_SEALS', name: 'Clamps for elastomer seals' },
    ],
    code: '130BSR050_sample',
    configurable: false,
    description: '',
    images: [
      {
        altText: 'Clamping Ring for Elastomer Seal, Plastic, DN 50 ISO-KF',
        format: 'product',
        imageType: 'PRIMARY',
        url: '/medias/?context=bWFzdGVyfGltYWdlc3wxODEwNjN8aW1hZ2UvcG5nfGgzMi9oOTcvODgyNDY4NzY4OTc1OHxkMGUyZjFjYjllZTdmZTc2ZTE5ODQzNTQwNmMzNDU1YWU1ZjE3M2Y1MDkwMDhkNzI2MDNjOWNkM2Y5NDVhNzdk',
      },
      {
        altText: 'Clamping Ring for Elastomer Seal, Plastic, DN 50 ISO-KF',
        format: 'product',
        galleryIndex: 0,
        imageType: 'GALLERY',
        url: '/medias/?context=bWFzdGVyfGltYWdlc3wxOTMzN3xpbWFnZS9wbmd8aDUyL2gzYy84ODI0Njg1NjkwOTEwfDk2MmIwNGM4NjRjNzY5ZjRkODUxMjQ1MDVlODVmNzdmMjIzMjQ0ZGRiMTIxM2JjMWY2MDRjZTI1MTRjMTVjNTQ',
      },
    ],
    name: 'Clamping Ring for Elastomer Seal, Plastic, DN 50 ISO-KF',
    orderNumber: '130BSR050',
    priceRange: {},
    productType: 'PRODUCT',
    purchasable: true,
    stock: { stockLevelStatus: 'inStock' },
    summary: '',
    typedFeatureList: [
      {
        code: 'Dimension',
        features: [
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3340.3340',
            comparable: true,
            featureUnit: { name: 'mm', symbol: 'mm', unitType: 'length' },
            featureValues: [{ value: '123' }],
            name: 'A',
            range: false,
            type: 'Dimension',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3341.3341',
            comparable: true,
            featureUnit: { name: 'mm', symbol: 'mm', unitType: 'length' },
            featureValues: [{ value: '95' }],
            name: 'B',
            range: false,
            type: 'Dimension',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3342.3342',
            comparable: true,
            featureUnit: { name: 'mm', symbol: 'mm', unitType: 'length' },
            featureValues: [{ value: '23' }],
            name: 'C',
            range: false,
            type: 'Dimension',
          },
        ],
      },
      {
        code: 'ClassifyData',
        features: [
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3795.3795',
            comparable: true,
            featureValues: [{ value: 'ISO-KF' }],
            name: 'Main flange type',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3796.3796',
            comparable: true,
            featureValues: [{ value: 'DN 50' }],
            name: 'Main flange size',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3798.3798',
            comparable: true,
            featureValues: [{ value: 'Plastic' }],
            name: 'Main material',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3806.3806',
            comparable: true,
            featureValues: [{ value: 'Fastening elements' }],
            name: 'Product type',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3807.3807',
            comparable: true,
            featureValues: [{ value: 'Clamps for elastomer seals' }],
            name: 'Product',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3809.3809',
            comparable: true,
            featureValues: [{ value: 'Components & Valves' }],
            name: 'Product category',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3919.3919',
            comparable: true,
            featureValues: [{ value: 'Components' }],
            name: 'Product SubCategory',
            range: false,
            type: 'ClassifyData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3950.3950',
            comparable: true,
            featureValues: [{ value: 'DN 50 ISO-KF' }],
            name: 'Connection flange',
            range: false,
            type: 'ClassifyData',
          },
        ],
      },
      {
        code: 'TechnicalData',
        features: [
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2204.2204',
            comparable: true,
            featureValues: [{ value: 'DN 50 ISO-KF' }],
            name: 'Nominal diameter',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_2628.2628',
            comparable: true,
            featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
            featureValues: [{ value: '500' }],
            name: 'Overpressure max.',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3282.3282',
            comparable: true,
            featureValues: [{ value: '-10 – 80 °C' }],
            name: 'Temperature range',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3712.3712',
            comparable: true,
            featureValues: [{ value: 'max. 2 Nm on wingnut' }],
            name: 'Torque',
            range: false,
            type: 'TechnicalData',
          },
          {
            code: 'pfeifferClassificationCatalog/1.0/cc_3742.3742',
            comparable: true,
            featureValues: [{ value: 'Plastic' }],
            name: 'Material',
            range: false,
            type: 'TechnicalData',
          },
        ],
      },
    ],
    url: '/Components-%26-Valves/Components/Fastening-elements/Clamps-for-elastomer-seals/Clamping-Ring-for-Elastomer-Seal%2C-Plastic%2C-DN-50-ISO-KF/p/130BSR050_sample',
  },
]

export default {}
