version: '3'

services:
  dev2:
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      # must match with the second entry in ports section
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      # Language
      - DEFAULT_LANGUAGE_CODE=${DEFAULT_LANGUAGE_CODE}
      - LANGUAGE_CODES=${LANGUAGE_CODES}
      # Region
      - REGION_CODES=${REGION_CODES}
      - DEFAULT_REGION_CODE=${DEFAULT_REGION_CODE}
      - CURRENT_REGION_CODE=${CURRENT_REGION_CODE}
      # storyblok
      - STORYBLOK_ACCESS_TOKEN=${STORYBLOK_ACCESS_TOKEN}
      - STORYBLOK_SPACE_ID=${STORYBLOK_SPACE_ID}
      - STORYBLOK_VERSION=${STORYBLOK_VERSION}
      - STORYBLOK_RESOLVE_RELATIONS=${STORYBLOK_RESOLVE_RELATIONS}
      - STORYBLOK_RESOLVE_LINKS=${STORYBLOK_RESOLVE_LINKS}
      - STORYBLOK_RESOLVE_ASSETS=${STORYBLOK_RESOLVE_ASSETS}
      - STORYBLOK_CONTENT_TYPES=${STORYBLOK_CONTENT_TYPES}
      - STORYBLOK_EXCLUDE_ROUTES=${STORYBLOK_EXCLUDE_ROUTES}
      - STORYBLOK_OAUTH_TOKEN=${STORYBLOK_OAUTH_TOKEN}
      - STORYBLOK_UPDATE_LINK_INTERVAL=${STORYBLOK_UPDATE_LINK_INTERVAL}
      - BASE_URL=${BASE_URL}
      - CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
      - CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}
      - CI_PROJECT_URL=${CI_PROJECT_URL}
      - USERCENTRICS_PRIVACY_PATH=${USERCENTRICS_PRIVACY_PATH}
      - USERCENTRICS_ID=${USERCENTRICS_ID}
      # hybris
      - SHOP_BASE_URL=${SHOP_BASE_URL}
      - SHOP_IMAGE_URL=${SHOP_IMAGE_URL}
      # keycloak
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      # Google Tag Manager for Google Analytics
      - GOOGLE_TAG_MANAGER_ID=${GOOGLE_TAG_MANAGER_ID}
      # empolis
      - EMPOLIS_TIMEOUT=${EMPOLIS_TIMEOUT}
      - EMPOLIS_STAGE=${EMPOLIS_STAGE}
      - EMPOLIS_PATH=${EMPOLIS_PATH}
      - EMPOLIS_GUEST_TOKEN_URL=${EMPOLIS_GUEST_TOKEN_URL}
      - EMPOLIS_SSO_PATH=${EMPOLIS_SSO_PATH}
      - EMPOLIS_AUTH_URL=${EMPOLIS_AUTH_URL}
      - EMPOLIS_USERNAME_CUSTOMER=${EMPOLIS_USERNAME_CUSTOMER}
      - EMPOLIS_PASSWORD_CUSTOMER=${EMPOLIS_PASSWORD_CUSTOMER}
      - EMPOLIS_USERNAME_INTERNAL_LEVEL_0=${EMPOLIS_USERNAME_INTERNAL_LEVEL_0}
      - EMPOLIS_PASSWORD_INTERNAL_LEVEL_0=${EMPOLIS_PASSWORD_INTERNAL_LEVEL_0}
      - EMPOLIS_USERNAME_INTERNAL_LEVEL_1=${EMPOLIS_USERNAME_INTERNAL_LEVEL_1}
      - EMPOLIS_PASSWORD_INTERNAL_LEVEL_1=${EMPOLIS_PASSWORD_INTERNAL_LEVEL_1}
      - EMPOLIS_USERNAME_INTERNAL_LEVEL_2=${EMPOLIS_USERNAME_INTERNAL_LEVEL_2}
      - EMPOLIS_PASSWORD_INTERNAL_LEVEL_2=${EMPOLIS_PASSWORD_INTERNAL_LEVEL_2}
      - EMPOLIS_CLIENT_ID=${EMPOLIS_CLIENT_ID}
      - EMPOLIS_CLIENT_SECRET=${EMPOLIS_CLIENT_SECRET}
      # vsm
      #- VSM_BASE_URL=https://testing-pv.vsm-cloud.com
      #- VSM_TECHNICAL_USER_TOKEN=10fff01e72e34e4fe33fbc84e5c6aa80017aac08
      # determines whether all service features (VSM) are shown or not
      #- SERVICE_PORTAL_ACTIVE=true
      # Vacuum Calculator
      - VACUUM_CALCULATOR_BASE_URL=${VACUUM_CALCULATOR_BASE_URL}
      # logging
      - CONSOLA_LEVEL=${CONSOLA_LEVEL} # { 0: 'error', 1: 'warn', 2: 'log', 3: 'info', 4: 'debug', 5: 'trace', Infinite: silent }

  dev2-oci:
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    ports:
      - "${OCI_PORT}:${OCI_PORT}"
    environment:
      - PORT=${OCI_PORT}
      - NODE_ENV=${NODE_ENV}
      # Language
      - DEFAULT_LANGUAGE_CODE=${DEFAULT_LANGUAGE_CODE}
      - LANGUAGE_CODES=${LANGUAGE_CODES}
      # Region
      - REGION_CODES=${REGION_CODES}
      - DEFAULT_REGION_CODE=oci
      - CURRENT_REGION_CODE=oci
      # storyblok
      - STORYBLOK_ACCESS_TOKEN=${STORYBLOK_ACCESS_TOKEN}
      - STORYBLOK_SPACE_ID=${STORYBLOK_SPACE_ID}
      - STORYBLOK_VERSION=${STORYBLOK_VERSION}
      - STORYBLOK_RESOLVE_RELATIONS=${STORYBLOK_RESOLVE_RELATIONS}
      - STORYBLOK_RESOLVE_LINKS=${STORYBLOK_RESOLVE_LINKS}
      - STORYBLOK_RESOLVE_ASSETS=${STORYBLOK_RESOLVE_ASSETS}
      - STORYBLOK_CONTENT_TYPES=${STORYBLOK_CONTENT_TYPES}
      - STORYBLOK_EXCLUDE_ROUTES=${STORYBLOK_EXCLUDE_ROUTES}
      - STORYBLOK_OAUTH_TOKEN=${STORYBLOK_OAUTH_TOKEN}
      - STORYBLOK_UPDATE_LINK_INTERVAL=${STORYBLOK_UPDATE_LINK_INTERVAL}
      - BASE_URL=${BASE_URL}
      - CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
      - CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}
      - CI_PROJECT_URL=${CI_PROJECT_URL}
      - USERCENTRICS_PRIVACY_PATH=${USERCENTRICS_PRIVACY_PATH}
      - USERCENTRICS_ID=${USERCENTRICS_ID}
      # node setup
      - IGNORE_SSL_CERT=${IGNORE_SSL_CERT} #don't trust all certificates
      # hybris
      - SHOP_BASE_URL=${SHOP_BASE_URL}
      - SHOP_IMAGE_URL=${SHOP_IMAGE_URL}
      # keycloak
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      # empolis
      - EMPOLIS_TIMEOUT=${EMPOLIS_TIMEOUT}
      - EMPOLIS_STAGE=${EMPOLIS_STAGE}
      - EMPOLIS_PATH=${EMPOLIS_PATH}
      - EMPOLIS_GUEST_TOKEN_URL=${EMPOLIS_GUEST_TOKEN_URL}
      - EMPOLIS_SSO_PATH=${EMPOLIS_SSO_PATH}
      - EMPOLIS_AUTH_URL=${EMPOLIS_AUTH_URL}
      - EMPOLIS_USERNAME_CUSTOMER=${EMPOLIS_USERNAME_CUSTOMER}
      - EMPOLIS_PASSWORD_CUSTOMER=${EMPOLIS_PASSWORD_CUSTOMER}
      - EMPOLIS_USERNAME_INTERNAL_LEVEL_0=${EMPOLIS_USERNAME_INTERNAL_LEVEL_0}
      - EMPOLIS_PASSWORD_INTERNAL_LEVEL_0=${EMPOLIS_PASSWORD_INTERNAL_LEVEL_0}
      - EMPOLIS_USERNAME_INTERNAL_LEVEL_1=${EMPOLIS_USERNAME_INTERNAL_LEVEL_1}
      - EMPOLIS_PASSWORD_INTERNAL_LEVEL_1=${EMPOLIS_PASSWORD_INTERNAL_LEVEL_1}
      - EMPOLIS_USERNAME_INTERNAL_LEVEL_2=${EMPOLIS_USERNAME_INTERNAL_LEVEL_2}
      - EMPOLIS_PASSWORD_INTERNAL_LEVEL_2=${EMPOLIS_PASSWORD_INTERNAL_LEVEL_2}
      - EMPOLIS_CLIENT_ID=${EMPOLIS_CLIENT_ID}
      - EMPOLIS_CLIENT_SECRET=${EMPOLIS_CLIENT_SECRET}
      # Google Tag Manager for Google Analytics
      - GOOGLE_TAG_MANAGER_ID=${GOOGLE_TAG_MANAGER_ID}
      - DISABLE_SECURITY_POLICY_FORM_ACTION_SELF=true
      # vsm
      #- VSM_BASE_URL=https://testing-pv.vsm-cloud.com
      #- VSM_TECHNICAL_USER_TOKEN=10fff01e72e34e4fe33fbc84e5c6aa80017aac08
      # determines whether all service features (VSM) are shown or not
      #- SERVICE_PORTAL_ACTIVE=true
      # logging
      - CONSOLA_LEVEL=${CONSOLA_LEVEL} # { 0: 'error', 1: 'warn', 2: 'log', 3: 'info', 4: 'debug', 5: 'trace', Infinite: silent }

