version: '3.8'

services:
  pvweb:
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_TAG_NAME}"
    deploy:
      mode: replicated
      replicas: ${CONTAINER_REPLICAS}
      placement:
        max_replicas_per_node: ${CONTAINER_REPLICAS_PER_NODE}
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      resources:
        limits:
          cpus: "${CONTAINER_LIMIT_CPU}"
          memory: "${CONTAINER_LIMIT_MEMORY}"
        reservations:
          cpus: "${CONTAINER_RESERVE_CPU}"
          memory: "${CONTAINER_RESERVE_MEMORY}"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV="${NODE_ENV}"
      # Language
      - DEFAULT_LANGUAGE_CODE="${DEFAULT_LANGUAGE_CODE}"
      - LANGUAGE_CODES="${LANGUAGE_CODES}"
      # Region
      - REGION_CODES="${REGION_CODES}"
      - DEFAULT_REGION_CODE="${DEFAULT_REGION_CODE}"
      - CURRENT_REGION_CODE="${CURRENT_REGION_CODE}"
      # storyblok
      - STORYBLOK_ACCESS_TOKEN="${STORYBLOK_ACCESS_TOKEN}"
      - STORYBLOK_SPACE_ID="${STORYBLOK_SPACE_ID}"
      - STORYBLOK_VERSION="${STORYBLOK_VERSION}"
      - STORYBLOK_RESOLVE_RELATIONS="${STORYBLOK_RESOLVE_RELATIONS}"
      - STORYBLOK_RESOLVE_LINKS="${STORYBLOK_RESOLVE_LINKS}"
      - STORYBLOK_RESOLVE_ASSETS="${STORYBLOK_RESOLVE_ASSETS}"
      - STORYBLOK_CONTENT_TYPES="${STORYBLOK_CONTENT_TYPES}"
      - STORYBLOK_EXCLUDE_ROUTES="${STORYBLOK_EXCLUDE_ROUTES}"
      - STORYBLOK_OAUTH_TOKEN="${STORYBLOK_OAUTH_TOKEN}"
      - BASE_URL="${CI_ENVIRONMENT_URL}"
      - CI_COMMIT_SHORT_SHA="${CI_COMMIT_SHORT_SHA}"
      - CI_COMMIT_REF_NAME="${CI_COMMIT_REF_NAME}"
      - CI_PROJECT_URL="${CI_PROJECT_URL}"
      - USERCENTRICS_PRIVACY_PATH="${USERCENTRICS_PRIVACY_PATH}"
      - USERCENTRICS_ID="${USERCENTRICS_ID}"
      # node setup
      #- REJECT_UNAUTHORIZED=true #don't trust all certificates
      #Storefront
      #- STOREFRONT_BASE_URL=${CI_ENVIRONMENT_URL}
      # hybris
      - SHOP_BASE_URL="${SHOP_BASE_URL}"
      - SHOP_IMAGE_URL="${SHOP_IMAGE_URL}"
