version: "3"

services:
  dev2:
    image: "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_ROMMIT_REF_SLUG}"
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # node setup
      - REJECT_UNAUTHORIZED=true #don't trust all certificates
      #Storefront
      - STOREFRONT_BASE_URL=${CI_ENVIRONMENT_URL}
      # storyblok
      #- STORYBLOK_API_PUBLIC_KEY= # dev public key
      #- STORYBLOK_API_PREVIEW_KEY= # dev preview key
      # hybris
      #- SHOP_BASE_URL=
      #- SHOP_IMAGE_URL=,
      #- SHOP_CLIENT_ID=pfeiffer_viewer
      #- SHOP_SECRET=secret,
      # vsm
      - VSM_BASE_URL=https://testing-pv.vsm-cloud.com
      - VSM_TECHNICAL_USER_TOKEN=10fff01e72e34e4fe33fbc84e5c6aa80017aac08
      # determines whether all service features (VSM) are shown or not
      - SERVICE_PORTAL_ACTIVE=true
      # logging
      - CONSOLA_LEVEL=3 # { 0: 'error', 1: 'warn', 2: 'log', 3: 'info', 4: 'debug', 5: 'trace', Infinite: silent }
      - LANGUAGES='en,de'
      # Google Tag Manager for Google Analytics
      - GOOGLE_TAG_MANAGER_ID=${CI_GOOGLE_TAG_MANAGER_ID}
