export const product = {
  alternativeOrderNumbers: ['PM P03 963'],
  bullets: [
    "The world's smallest series-production turbopump",
    'A powerful, rugged turbopump with a pumping speed of 10 l/s for N<sub>2</sub>',
    'DN 25 connection',
    'Drive electronics TC 110 and power supply OPS 040 integrated',
    'Mobile usable',
    'Requires no additional cooling',
    'Electronic connection in direction of fore-vacuum connection',
  ],
  categories: [{ id: 'HIPACE__10', name: 'HiPace® 10' }],
  categoryPath: [
    { id: 'PUMPS', name: 'Pumps' },
    { id: 'TURBOPUMPS', name: 'Turbopumps' },
    { id: 'HIPACE__10', name: 'HiPace® 10' },
  ],
  code: 'PM_P03_963_B_sample',
  configurable: false,
  description: '',
  dimensionImage: {
    altText:
      'Dimensions for HiPace® 10 with TC 110 and power supply pack OPS 40, DN 25',
    format: '300Wx300H',
    url: '/medias/?context=bWFzdGVyfGltYWdlc3wzNjYwNXxpbWFnZS9wbmd8aGFjL2gzMC84ODI0Njg2NzcyMjU0fDVmYjA1YzFiZjYyOGQzYjVkNTA3MjBmMzg3ZGY3MDExZTY4Y2M0MGE4YTFmNWFiNmI0ZDMzMTQ1ODYyMjI0NjY',
  },
  footnotes: ['TestFootNote1'],
  images: [
    {
      altText: 'HiPace® 10 with TC 110 and power supply pack OPS 40, DN 25',
      format: 'product',
      imageType: 'PRIMARY',
      url: '/medias/?context=bWFzdGVyfGltYWdlc3w1MDc0MDJ8aW1hZ2UvcG5nfGg3NC9oZmQvODgyNDY4ODU3NDQ5NHxjYmUxYmNmN2Y5OTgwNDBiZWFlNTZiMjhiNzE5MjYyYTZjYTg5NWM0YjhiNGQ3OGQyMjYxOGMyNmU2ZGQzODI3',
    },
    {
      altText: 'HiPace® 10 with TC 110 and power supply pack OPS 40, DN 25',
      format: 'product',
      galleryIndex: 0,
      imageType: 'GALLERY',
      url: '/medias/?context=bWFzdGVyfGltYWdlc3wyMjUxM3xpbWFnZS9wbmd8aDc0L2gyNi84ODI0Njg2NDc3MzQyfDY3MTYwYjE5MzdhMGZiMWRmY2ViNzIzODViY2QzMTc0MTY0NTFjYTZmMTFhMzgyOTU1NzJiYzA4ZTMyOTAwYWU',
    },
    {
      altText: 'HiPace® 10 with TC 110 and power supply pack OPS 40, DN 25',
      format: 'product',
      galleryIndex: 1,
      imageType: 'GALLERY',
      url: '/medias/?context=bWFzdGVyfGltYWdlc3wzNjYwNXxpbWFnZS9wbmd8aGFjL2gzMC84ODI0Njg2NzcyMjU0fDVmYjA1YzFiZjYyOGQzYjVkNTA3MjBmMzg3ZGY3MDExZTY4Y2M0MGE4YTFmNWFiNmI0ZDMzMTQ1ODYyMjI0NjY',
    },
  ],
  master: '334565dc-8d3a-4728-a2d6-e703d355cd6b_sample',
  name: 'HiPace® 10 with TC 110 and power supply pack OPS 40, DN 25',
  orderNumber: 'PM P03 963 B',
  priceRange: {},
  productReferences: [
    {
      referenceType: 'ACCESSORIES',
      target: {
        code: 'PM_Z01_205_B_sample',
        name: 'TVV 001, fore-vacuum safety valve, 230 V AC',
        url: '/c/TVV-001%2C-fore-vacuum-safety-valve%2C-230-V-AC/p/PM_Z01_205_B_sample',
      },
      preselected: false,
    },
    {
      referenceType: 'ACCESSORIES',
      target: {
        code: 'PM_Z01_206_B_sample',
        name: 'TVV 001, fore-vacuum safety valve, 115 V AC',
        url: '/c/TVV-001%2C-fore-vacuum-safety-valve%2C-115-V-AC/p/PM_Z01_206_B_sample',
      },
      preselected: false,
    },
    {
      referenceType: 'ACCESSORIES',
      target: {
        code: 'PT_R70_000_sample',
        name: 'TIC 010, adapter for two sensors',
        url: '/c/TIC-010%2C-adapter-for-two-sensors/p/PT_R70_000_sample',
      },
      preselected: false,
    },
    {
      referenceType: 'SPAREPART',
      target: {
        code: 'P_4768_052_FE_sample',
        name: 'PTC-resistor tripping device for motor protection 24 V AC/DC',
        url: '/c/PTC-resistor-tripping-device-for-motor-protection-24-V-AC-DC/p/P_4768_052_FE_sample',
      },
      preselected: false,
    },
    {
      referenceType: 'RECOMMENDEDACCESSORIES',
      target: {
        code: 'PM_Z01_205_B_sample',
        name: 'TVV 001, fore-vacuum safety valve, 230 V AC',
        url: '/c/TVV-001%2C-fore-vacuum-safety-valve%2C-230-V-AC/p/PM_Z01_205_B_sample',
      },
      preselected: false,
    },
    {
      referenceType: 'RECOMMENDEDACCESSORIES',
      target: {
        code: 'PT_R70_000_sample',
        name: 'TIC 010, adapter for two sensors',
        url: '/c/TIC-010%2C-adapter-for-two-sensors/p/PT_R70_000_sample',
      },
      preselected: false,
    },
    {
      referenceType: 'CONSUMABLE',
      target: {
        code: 'PK_050_111_sample',
        name: 'Mains cable 115/230 V without plug, rubber connector (right angle), 3 m',
        url: '/c/Mains-cable-115-230-V-without-plug%2C-rubber-connector-%28right-angle%29%2C-3-m/p/PK_050_111_sample',
      },
      preselected: false,
    },
  ],
  productType: 'VARIANTPRODUCT',
  purchasable: true,
  stock: { stockLevelStatus: 'inStock' },
  summary: '',
  typedFeatureList: [
    {
      code: 'DownloadData',
      features: [
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_1107.1107',
          comparable: true,
          featureValues: [{ value: 'Pfeiffer-Vacuum-TurboViewer.zip' }],
          name: 'Software',
          range: false,
          type: 'DownloadData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_1108.1108',
          comparable: true,
          featureValues: [{ value: 'Installationshinweis_LabView.pdf' }],
          name: 'Software',
          range: false,
          type: 'DownloadData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3161.3161',
          comparable: true,
          featureValues: [{ value: 'PT0204' }],
          name: 'Operating instructions',
          range: false,
          type: 'DownloadData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3333.3333',
          comparable: true,
          featureValues: [{ value: 'PT0246' }],
          name: 'Operating instructions',
          range: false,
          type: 'DownloadData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3782.3782',
          comparable: true,
          featureValues: [{ value: 'Pfeiffer_Vacuum.zip' }],
          name: 'Software',
          range: false,
          type: 'DownloadData',
        },
      ],
    },
    {
      code: 'ClassifyData',
      features: [
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3389.3389',
          comparable: true,
          featureValues: [{ value: '5E-5 hPa' }],
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3390.3390',
          comparable: true,
          featureValues: [{ value: '5E-5 hPa' }],
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3795.3795',
          comparable: true,
          featureValues: [{ value: 'ISO-KF' }],
          name: 'Main flange type',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3796.3796',
          comparable: true,
          featureValues: [{ value: 'DN 25' }],
          name: 'Main flange size',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3806.3806',
          comparable: true,
          featureValues: [{ value: 'Turbopumps' }],
          name: 'Product type',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3807.3807',
          comparable: true,
          featureValues: [{ value: 'HiPace® 10' }],
          name: 'Product',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3809.3809',
          comparable: true,
          featureValues: [{ value: 'Pumps' }],
          name: 'Product category',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3912.3912',
          comparable: true,
          featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
          featureValues: [{ value: '5.0E-5' }],
          name: 'Vacuum range min',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3913.3913',
          comparable: true,
          featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
          featureValues: [{ value: '25' }],
          name: 'Vacuum range max',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3914.3914',
          comparable: true,
          featureValues: [{ value: 'Integrated electronic drive unit' }],
          name: 'Electronic drive unit location',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3917.3917',
          comparable: true,
          featureUnit: { name: 'm³/h', symbol: 'm³/h', unitType: 'volumeflow' },
          featureValues: [{ value: '36' }],
          name: 'Pumping Speed Class',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3918.3918',
          comparable: true,
          featureValues: [{ value: 'HiPace® 10' }],
          name: 'Master-Product',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3925.3925',
          comparable: true,
          featureValues: [{ value: '4517' }],
          name: 'Product-Master-ShortID',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3929.3929',
          comparable: true,
          featureValues: [{ value: 'Integrated power supply pack' }],
          name: 'Power supply location',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3930.3930',
          comparable: true,
          featureValues: [{ value: 'RS-485, Remote' }],
          name: 'I/O Interfaces',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3931.3931',
          comparable: true,
          featureValues: [{ value: '24 V DC' }],
          name: 'Operating voltage',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3941.3941',
          comparable: true,
          featureValues: [
            {
              value:
                'Electronic connection in direction of fore-vacuum connection',
            },
          ],
          name: 'Specifics',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3942.3942',
          comparable: true,
          featureValues: [{ value: 'Ideal for mobile applications' }],
          name: 'Special Product Version',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3945.3945',
          comparable: true,
          featureValues: [{ value: 'with TC 110' }],
          name: 'Electronic drive unit',
          range: false,
          type: 'ClassifyData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3950.3950',
          comparable: true,
          featureValues: [{ value: 'DN 25' }],
          name: 'Connection flange',
          range: false,
          type: 'ClassifyData',
        },
      ],
    },
    {
      code: 'TechnicalData',
      features: [
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2021.2021',
          comparable: true,
          featureValues: [{ value: 'YES' }],
          name: 'Particle intake',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2023.2023',
          comparable: true,
          featureValues: [{ value: 'with TC 110' }],
          name: 'Electronic drive unit',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2055.2055',
          comparable: true,
          featureUnit: { name: 'W', symbol: 'W', unitType: 'power' },
          featureValues: [{ value: '28.8' }],
          name: 'Power consumption max.',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2090.2090',
          comparable: true,
          featureUnit: {
            name: 'mT',
            symbol: 'mT',
            unitType: 'magneticfluxdensity',
          },
          featureValues: [{ value: '3' }],
          name: 'Permissible radial magnetic field max.',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2096.2096',
          comparable: true,
          featureUnit: { name: 'min', symbol: 'min', unitType: 'time' },
          featureValues: [{ value: '0.9' }],
          name: 'Run-up time',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2150.2150',
          comparable: true,
          featureValues: [{ value: 'IP30' }],
          name: 'Protection degree',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2157.2157',
          comparable: true,
          featureValues: [{ value: 'Arbitrary' }],
          name: 'Mounting orientation',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2180.2180',
          comparable: true,
          featureValues: [{ value: 'Ball bearing' }],
          name: 'Bearing',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2207.2207',
          comparable: true,
          featureValues: [{ value: '50 – 100 %' }],
          name: 'Rotation speed variable',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2366.2366',
          comparable: true,
          featureValues: [{ value: 'RS-485, Remote' }],
          name: 'I/O interfaces',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2424.2424',
          comparable: true,
          featureValues: [{ value: "DN 16 ISO-KF/G 1/8''" }],
          name: 'Connection flange (out)',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2428.2428',
          comparable: true,
          featureValues: [{ value: 'DN 25' }],
          name: 'Connection flange (in)',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2673.2673',
          comparable: true,
          featureUnit: { name: 'kg', symbol: 'kg', unitType: 'weight' },
          featureValues: [{ value: '2' }],
          name: 'Weight',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2707.2707',
          comparable: true,
          featureValues: [{ value: '24 (± 5 %) V DC' }],
          name: 'Operating voltage: V DC',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2730.2730',
          comparable: true,
          featureUnit: {
            name: 'rpm',
            symbol: 'rpm',
            unitType: 'revolutionperminute',
          },
          featureValues: [{ value: '90000' }],
          name: 'Rotation speed ± 2 %',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2750.2750',
          comparable: true,
          featureValues: [{ value: '1,2 A' }],
          name: 'Current, max.',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_2977.2977',
          comparable: true,
          featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
          featureValues: [{ value: '< 5 · 10<sup>-5</sup>' }],
          name: 'Final pressure according to PNEUROP',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3119.3119',
          comparable: true,
          featureValues: [{ value: 'YES' }],
          name: 'Integrated power supply pack',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3167.3167',
          comparable: true,
          featureUnit: { name: 'm³/s', symbol: 'm³/s', unitType: 'volumeflow' },
          featureValues: [{ value: '6' }],
          name: 'Pumping speed for He',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3183.3183',
          comparable: true,
          featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
          featureValues: [{ value: '25' }],
          name: 'Fore-vacuum max. for N<sub>2</sub>',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3313.3313',
          comparable: true,
          featureValues: [{ value: '≤50 dB(A)' }],
          name: 'Sound pressure level',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3335.3335',
          comparable: true,
          featureUnit: { name: 'hPa', symbol: 'hPa', unitType: 'pressure' },
          featureValues: [{ value: '< 5 · 10<sup>-5</sup>' }],
          name: 'Final pressure without gas ballast',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3375.3375',
          comparable: true,
          featureUnit: { name: 'm³/s', symbol: 'm³/s', unitType: 'volumeflow' },
          featureValues: [{ value: '10' }],
          name: 'Pumping speed for N<sub>2</sub>',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3412.3412',
          comparable: true,
          featureValues: [{ value: '2.5 · 10<sup>7</sup>' }],
          name: 'Compression ratio for Ar',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3414.3414',
          comparable: true,
          featureValues: [{ value: '3 · 10<sup>2</sup>' }],
          name: 'Compression ratio for H<sub>2</sub>',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3415.3415',
          comparable: true,
          featureValues: [{ value: '3 · 10<sup>3</sup>' }],
          name: 'Compression ratio for He',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3416.3416',
          comparable: true,
          featureValues: [{ value: '3 · 10<sup>6</sup>' }],
          name: 'Compression ratio for N<sub>2</sub>',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3430.3430',
          comparable: true,
          featureUnit: {
            name: 'hPa·l/s',
            symbol: 'hPa·l/s',
            unitType: 'throughput',
          },
          featureValues: [{ value: '0.37' }],
          name: 'Gas throughput at final rotation speed for Ar',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3433.3433',
          comparable: true,
          featureUnit: {
            name: 'hPa·l/s',
            symbol: 'hPa·l/s',
            unitType: 'throughput',
          },
          featureValues: [{ value: '0.48' }],
          name: 'Gas throughput at final rotation speed for He',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3432.3432',
          comparable: true,
          featureUnit: {
            name: 'hPa·l/s',
            symbol: 'hPa·l/s',
            unitType: 'throughput',
          },
          featureValues: [{ value: '2.78' }],
          name: 'Gas throughput at final rotation speed for H<sub>2</sub>',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3434.3434',
          comparable: true,
          featureUnit: {
            name: 'hPa·l/s',
            symbol: 'hPa·l/s',
            unitType: 'throughput',
          },
          featureValues: [{ value: '0.37' }],
          name: 'Gas throughput at final rotation speed for N<sub>2</sub>',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3436.3436',
          comparable: true,
          featureUnit: { name: 'm³/s', symbol: 'm³/s', unitType: 'volumeflow' },
          featureValues: [{ value: '11.5' }],
          name: 'Pumping speed for Ar',
          range: false,
          type: 'TechnicalData',
        },
        {
          code: 'pfeifferClassificationCatalog/1.0/cc_3438.3438',
          comparable: true,
          featureUnit: { name: 'm³/s', symbol: 'm³/s', unitType: 'volumeflow' },
          featureValues: [{ value: '3.7' }],
          name: 'Pumping speed for H<sub>2</sub>',
          range: false,
          type: 'TechnicalData',
        },
      ],
    },
  ],
  url: '/Pumps/Turbopumps/HiPace%C2%AE-10/HiPace%C2%AE-10-with-TC-110-and-power-supply-pack-OPS-40%2C-DN-25/p/PM_P03_963_B_sample',
}
