export default {
  name: 'HomeStageCarousel',
  display_name: 'Home Stage Carousel',
  schema: {
    slides: {
      type: 'bloks',
      display_name: 'Slides',
      restrict_components: true,
      component_whitelist: ['TeaserCard'],
      required: true,
      pos: 1,
    },
    autoplay: {
      type: 'boolean',
      display_name: 'Autoplay',
      description: 'Enables autoplay on carousel.',
      pos: 2,
    },
    infinite: {
      type: 'boolean',
      display_name: 'Inifinite',
      description: 'Enables infinite wrap around slides on carousel.',
      pos: 3,
    },
  },
  image: null,
  preview_field: null,
  preview_tmpl: '<div>{{ label }}</div>',
  is_root: false,
  is_nestable: true,
  all_presets: [],
  preset_id: null,
  real_name: 'HomeStageCarousel',
  component_group_uuid: null,
}
