export default {
  name: 'Header',
  display_name: 'Header',
  schema: {
    navigationEntries: {
      type: 'bloks',
      restrict_components: true,
      component_whitelist: ['MainNavLinkLevel0', 'MainNavLinkMobile'],
      pos: 1,
      description: 'Navigation bar entries displayed on the left side.',
    },
    flyoutLinks: {
      type: 'bloks',
      restrict_components: true,
      component_whitelist: ['FlyoutEntry'],
      pos: 2,
      maximum: 4,
      description: 'Links on the upper right',
    },
    shopNavigationLinks: {
      type: 'bloks',
      restrict_components: true,
      component_whitelist: ['ShopNavigationEntry'],
      pos: 3,
      description: 'Shop Navigation Entries',
    },
  },
  image: null,
  preview_field: null,
  is_root: false,
  preview_tmpl: null,
  is_nestable: true,
  all_presets: [],
  preset_id: null,
  real_name: 'Header',
  component_group_name: 'Global',
}
