export const path = '/default/products/hicube/'
export const breadcrumbResult = [
  { href: '/default', name: 'Zu Hause' },
  { href: '/default/products/hicube', name: 'Hicube' },
]

export const cmsLinks = [
  {
    id: 125502712,
    slug: 'default/',
    name: 'Home',
    is_folder: false,
    parent_id: 125502710,
    published: true,
    path: null,
    position: -230,
    uuid: 'c0b766d9-bf1d-4a06-a3cb-b9f0e8d39125',
    is_startpage: true,
    real_path: '/default/',
    alternates: [{ path: 'default/', name: 'Zu Hause', lang: 'de' }],
  },
  {
    id: 125502714,
    slug: 'default/products',
    name: 'Products',
    is_folder: true,
    parent_id: 125502710,
    published: false,
    path: null,
    position: -180,
    uuid: 'a05a4b87-2a2f-4e7d-8327-7a5d65634de1',
    is_startpage: false,
    real_path: '/default/products',
    alternates: [{ path: 'default/products', name: null, lang: 'de' }],
  },
  {
    id: 125502713,
    slug: 'default/accordion',
    name: 'Accordion',
    is_folder: false,
    parent_id: 125502710,
    published: true,
    path: null,
    position: -100,
    uuid: '4cd1434c-4957-460b-8525-b05565ebafdb',
    is_startpage: false,
    real_path: '/default/accordion',
    alternates: [{ path: 'default/accordion', name: null, lang: 'de' }],
  },
  {
    id: 125502720,
    slug: 'default/products/trio2',
    name: 'Trio2',
    is_folder: false,
    parent_id: 125502714,
    published: false,
    path: null,
    position: -40,
    uuid: 'ed59fcdb-df75-4a90-b985-f71e004c3314',
    is_startpage: false,
    real_path: '/default/products/trio2',
    alternates: [{ path: 'default/products/trio2', name: null, lang: 'de' }],
  },
  {
    id: 125502719,
    slug: 'default/products/trio',
    name: 'Trio',
    is_folder: false,
    parent_id: 125502714,
    published: false,
    path: null,
    position: -30,
    uuid: '00a6a346-e50b-4dbc-b276-7c8fe58f4db4',
    is_startpage: false,
    real_path: '/default/products/trio',
    alternates: [{ path: 'default/products/trio', name: null, lang: 'de' }],
  },
  {
    id: 125502718,
    slug: 'default/products/duo',
    name: 'Duo',
    is_folder: false,
    parent_id: 125502714,
    published: false,
    path: null,
    position: -20,
    uuid: '366c167e-8d4e-4475-80c7-b540b7eb248a',
    is_startpage: false,
    real_path: '/default/products/duo',
    alternates: [{ path: 'default/products/duo', name: null, lang: 'de' }],
  },
  {
    id: 125502717,
    slug: 'default/products/hicube',
    name: 'Hicube',
    is_folder: false,
    parent_id: 125502714,
    published: true,
    path: null,
    position: -10,
    uuid: '70ff68c6-2cfb-4a0c-86c9-e5fb85b761c9',
    is_startpage: false,
    real_path: '/default/products/hicube',
    alternates: [{ path: 'default/products/hicube', name: null, lang: 'de' }],
  },
  {
    id: 125502710,
    slug: 'default',
    name: 'default',
    is_folder: true,
    parent_id: 0,
    published: false,
    path: '',
    position: -10,
    uuid: '4118f6b0-3c2b-4eac-a570-f5003f35a240',
    is_startpage: false,
    real_path: '/default',
    alternates: [{ path: 'default', name: null, lang: 'de' }],
  },
  {
    id: 125502711,
    slug: 'default/templates',
    name: 'Templates',
    is_folder: true,
    parent_id: 125502710,
    published: false,
    path: null,
    position: 0,
    uuid: '43a786f9-5521-48d0-bc7d-901a0f9039bf',
    is_startpage: false,
    real_path: '/default/templates',
    alternates: [{ path: 'default/templates', name: null, lang: 'de' }],
  },
  {
    id: 125502715,
    slug: 'default/templates/defaultpageconfiguration',
    name: 'DefaultPageConfiguration',
    is_folder: false,
    parent_id: 125502711,
    published: true,
    path: null,
    position: 0,
    uuid: '98223465-2e9e-4a0e-a4a5-46c10af6c900',
    is_startpage: false,
    real_path: '/default/templates/defaultpageconfiguration',
    alternates: [
      {
        path: 'default/templates/defaultpageconfiguration',
        name: null,
        lang: 'de',
      },
    ],
  },
  {
    id: 125502716,
    slug: 'default/products/hipace',
    name: 'Hipace',
    is_folder: false,
    parent_id: 125502714,
    published: true,
    path: null,
    position: 0,
    uuid: '9d56b5f6-8382-4eeb-96b5-feb25cbcf3b1',
    is_startpage: false,
    real_path: '/default/products/hipace',
    alternates: [{ path: 'default/products/hipace', name: null, lang: 'de' }],
  },
]

export default {}
