export default {
  name: 'HomeStageContent',
  display_name: 'HomeStageContent',
  schema: {
    headline: {
      type: 'text',
      translatable: true,
      required: true,
      display_name: 'Headline',
      max_length: '50',
      pos: 1,
    },
    teaserText: {
      type: 'textarea',
      translatable: true,
      display_name: 'Teaser Text',
      max_length: '250',
      pos: 3,
    },
    links: {
      type: 'bloks',
      restrict_components: true,
      maximum: 2,
      component_whitelist: ['TextLink'],
      display_name: 'Links',
    },
    buttons: {
      type: 'bloks',
      restrict_components: true,
      maximum: 2,
      component_whitelist: ['Button'],
      display_name: 'Buttons',
    },
  },
  image: null,
  preview_field: null,
  is_root: false,
  is_nestable: true,
  all_presets: [],
  preset_id: null,
  real_name: 'HomeStage',
  component_group_uuid: null,
}
