export const REFERENCE_GROUPS = {
  ACCESSORIES: 'ACCESSORIES',
  CONSUMABLE: 'CONSUMABLE',
  SPAREPART: 'SPAREPART',
  RECOMMENDEDACCESSORIES: 'RECOMMENDEDACCESSORIES',
}

export const REFERENCE_GROUPS_LIST = Object.values(REFERENCE_GROUPS)
